-- AI-01-C2 neutral schema extracted from immutable MySQL 0001.
CREATE TABLE IF NOT EXISTS `users` (`uniqueid` INTEGER auto_increment , `login` VARCHAR(255), `name` VARCHAR(255), `passwd` VARCHAR(255), `email` VARCHAR(255), `exten` VARCHAR(255), `level` INTEGER DEFAULT 2, `role` INTEGER, `numbers_id` INTEGER, `permit_extens` VARCHAR(255), `listbook_edit` INTEGER DEFAULT 0, `oper_chanspy` INTEGER DEFAULT 0, `outbound_posttime` INTEGER DEFAULT 0, `suspension_time` INTEGER DEFAULT 0, `inactive_time` INTEGER DEFAULT 0, `vpbx_user_uid` INTEGER DEFAULT 0, `activationCode` VARCHAR(255), `activationExpires` BIGINT, `isActivated` TINYINT(1) DEFAULT false, `avatar` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`uniqueid`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `user_sessions` (`id` INTEGER auto_increment , `user_id` INTEGER NOT NULL, `refreshToken` VARCHAR(512) NOT NULL, `userAgent` TEXT, `ipAddress` VARCHAR(45), `expiresAt` BIGINT NOT NULL, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `tenants` (`id` INTEGER auto_increment , `uid` VARCHAR(36) NOT NULL, `name` VARCHAR(255) NOT NULL, `slug` VARCHAR(128), `owner_user_id` INTEGER NOT NULL, `vpbx_user_uid` INTEGER NOT NULL, `status` ENUM('trial', 'active', 'suspended', 'cancelled') DEFAULT 'trial', `trial_ends_at` DATETIME, `email` VARCHAR(255), `phone` VARCHAR(32), `company_inn` VARCHAR(32), `max_extensions` INTEGER DEFAULT 10, `max_trunks` INTEGER DEFAULT 2, `max_queues` INTEGER DEFAULT 3, `created_by` INTEGER, `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `action_logs` (`id` INTEGER auto_increment , `user_id` INTEGER NOT NULL, `action` VARCHAR(64) NOT NULL, `entity_type` VARCHAR(64) NOT NULL, `entity_id` INTEGER, `details` TEXT, `vpbx_user_uid` INTEGER NOT NULL, `status` VARCHAR(16) NOT NULL DEFAULT 'success', `created_at` DATETIME, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `roles` (`id` INTEGER auto_increment , `name` VARCHAR(255), `role` TEXT, `comment` VARCHAR(255), `vpbx_user_uid` INTEGER DEFAULT 0, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `modules_registry` (`id` INTEGER auto_increment , `code` VARCHAR(64) NOT NULL UNIQUE, `name` VARCHAR(128) NOT NULL, `description` TEXT, `version` VARCHAR(16) DEFAULT '1.0.0', `category` ENUM('pbx', 'calls', 'analytics', 'integrations', 'admin') DEFAULT 'pbx', `is_core` TINYINT(1) DEFAULT false, `is_paid` TINYINT(1) DEFAULT false, `price_monthly` DECIMAL(10,2) DEFAULT 0, `is_published` TINYINT(1) DEFAULT true, `requires_cloud` TINYINT(1) DEFAULT false, `dependencies` JSON, `created_at` DATETIME, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `tenant_modules` (`id` INTEGER auto_increment , `tenant_id` INTEGER NOT NULL, `module_code` VARCHAR(64) NOT NULL, `status` ENUM('active', 'inactive', 'trial', 'expired') DEFAULT 'active', `activated_at` DATETIME, `expires_at` DATETIME, `billing_cycle` ENUM('monthly', 'yearly', 'lifetime') DEFAULT 'monthly', `last_billed_at` DATETIME, `config` JSON, PRIMARY KEY (`id`), UNIQUE INDEX `uq_tenant_module` (`tenant_id`, `module_code`), INDEX `idx_tm_tenant` (`tenant_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `cc_ai_providers` (`uid` INTEGER auto_increment , `name` VARCHAR(128) NOT NULL, `kind` ENUM('online', 'local', 'custom') NOT NULL, `vendor` VARCHAR(32) NOT NULL, `endpoint` VARCHAR(512) NOT NULL, `auth_type` ENUM('bearer', 'api_key_header', 'none', 'custom') DEFAULT 'bearer', `encrypted_api_key` TEXT, `capabilities` JSON NOT NULL, `defaults` JSON, `pricing` JSON NOT NULL, `enabled` TINYINT(1) NOT NULL DEFAULT true, `vpbx_user_uid` INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (`uid`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `cloud_settings` (`id` INTEGER auto_increment , `key` VARCHAR(128) NOT NULL UNIQUE, `value` TEXT, `description` VARCHAR(255), `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `hub_modules` (`id` INTEGER auto_increment , `code` VARCHAR(64) NOT NULL UNIQUE, `name` VARCHAR(128) NOT NULL, `kind` ENUM('base', 'market') NOT NULL DEFAULT 'base', `sort_order` INTEGER DEFAULT 0, `requires_cloud` TINYINT(1) DEFAULT false, PRIMARY KEY (`id`), UNIQUE INDEX `uq_hub_modules_code` (`code`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS `hub_module_pages` (`id` INTEGER auto_increment , `hub_code` VARCHAR(64) NOT NULL, `page_code` VARCHAR(64) NOT NULL, `path` VARCHAR(255), `sort_order` INTEGER DEFAULT 0, PRIMARY KEY (`id`), FOREIGN KEY (`hub_code`) REFERENCES `hub_modules` (`code`) ON DELETE NO ACTION ON UPDATE CASCADE, UNIQUE INDEX `uq_hub_module_page` (`hub_code`, `page_code`), INDEX `idx_hub_module_pages_hub` (`hub_code`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;
