CREATE TABLE queue_log (
  id BIGINT NOT NULL AUTO_INCREMENT,
  time VARCHAR(32) NOT NULL DEFAULT '',
  callid VARCHAR(80) NOT NULL DEFAULT '',
  queuename VARCHAR(80) NOT NULL DEFAULT '',
  agent VARCHAR(80) NOT NULL DEFAULT '',
  event VARCHAR(32) NOT NULL DEFAULT '',
  data VARCHAR(255) NULL,
  data1 VARCHAR(100) NULL,
  data2 VARCHAR(100) NULL,
  data3 VARCHAR(100) NULL,
  data4 VARCHAR(100) NULL,
  data5 VARCHAR(100) NULL,
  userfield VARCHAR(255) NULL,
  event_id CHAR(64) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_queue_log_event_id (event_id),
  KEY idx_queue_log_time (time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE cel (
  id BIGINT NOT NULL AUTO_INCREMENT,
  eventtype VARCHAR(32) NOT NULL DEFAULT '',
  eventtime DATETIME NOT NULL,
  userdeftype VARCHAR(255) NOT NULL DEFAULT '',
  cid_name VARCHAR(80) NOT NULL DEFAULT '',
  cid_num VARCHAR(80) NOT NULL DEFAULT '',
  cid_ani VARCHAR(80) NOT NULL DEFAULT '',
  cid_rdnis VARCHAR(80) NOT NULL DEFAULT '',
  cid_dnid VARCHAR(80) NOT NULL DEFAULT '',
  exten VARCHAR(80) NOT NULL DEFAULT '',
  context VARCHAR(80) NOT NULL DEFAULT '',
  channame VARCHAR(80) NOT NULL DEFAULT '',
  appname VARCHAR(80) NOT NULL DEFAULT '',
  appdata VARCHAR(255) NOT NULL DEFAULT '',
  amaflags INTEGER NOT NULL DEFAULT 0,
  accountcode VARCHAR(20) NOT NULL DEFAULT '',
  uniqueid VARCHAR(80) NOT NULL DEFAULT '',
  linkedid VARCHAR(80) NOT NULL DEFAULT '',
  peer VARCHAR(80) NOT NULL DEFAULT '',
  userfield VARCHAR(255) NULL,
  extra VARCHAR(512) NULL,
  event_id CHAR(64) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_cel_event_id (event_id),
  KEY idx_cel_uniqueid (uniqueid),
  KEY idx_cel_eventtime (eventtime)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
