/**
 * MixMonitor / ffmpeg helpers for route call recording.
 *
 * Stereo uses Asterisk MixMonitor option `D` (interleaved RX/TX channels).
 * Requires `.raw` extension — other extensions produce corrupted stereo output.
 */

export interface RouteRecordingOptions {
  record_all?: boolean;
  record_stereo?: boolean;
}

/** MixMonitor flags: `b` = record only when bridged; `D` = stereo interleaved. */
export function buildMixMonitorFlags(opts: RouteRecordingOptions): string {
  let flags = '';
  if (opts.record_all !== true) flags += 'b';
  if (opts.record_stereo === true) flags += 'D';
  return flags;
}

const UUID_FILE = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

export function durableCaptureFileBase(recordingUid: string): string {
  if (!UUID_FILE.test(recordingUid)) {
    throw new Error('durable capture filename must be a server UUID');
  }
  return recordingUid;
}

export function buildStopMixMonitor(recorderId: string): string {
  return `StopMixMonitor(${recorderId})`;
}

export function mixMonitorWithRecorderId(
  file: string, flags: string, recorderId: string, postprocess?: string,
): string {
  return `MixMonitor(${file},${flags},${postprocess ?? ''},${recorderId})`;
}

export function shouldRunLegacyFfmpegHangup(durableCapture: boolean): boolean {
  return !durableCapture;
}

export function getRecordingSourceExtension(stereo: boolean): 'wav' | 'raw' {
  return stereo ? 'raw' : 'wav';
}

export type RecordingDialplanInput = {
  vpbxUserUid: number;
  durable: boolean;
  recordStereo: boolean;
  recordAll: boolean;
  hangupWebhook: boolean;
  hangupContext?: string;
  /** When set, always push hangup_handler so analytics notify can run after StopMixMonitor (D-02). */
  analyticsProjectId?: string | null;
};

/** MixMonitor + hangup_handler lines used by generated routes (`routes.service`). */
export function recordingDialplanLines(input: RecordingDialplanInput): string[] {
  const flags = buildMixMonitorFlags({
    record_all: input.recordAll,
    record_stereo: input.recordStereo,
  });
  const recExt = getRecordingSourceExtension(input.recordStereo);
  const rpath = `${input.vpbxUserUid}/calls`;
  const recBase = `/usr/records/${rpath}/\${path}/\${fname}`;
  const lines = [
    'same => n,Set(__path=${STRFTIME(${EPOCH},,%Y%m%d)})',
    `same => n,System(mkdir -p /usr/records/${rpath}/\${path})`,
  ];
  if (input.durable) {
    lines.push('same => n,Set(__DURABLE_CAPTURE=1)');
    lines.push('same => n,Set(__fname=${SHELL(cat /proc/sys/kernel/random/uuid | tr -d \\\\n)})');
    lines.push('same => n,Set(__RECORDER_ID=${fname})');
    if (input.recordStereo) lines.push('same => n,Set(__REC_STEREO=1)');
    lines.push(`same => n,Set(CDR(record)=${rpath}/\${path}/\${fname})`);
    lines.push(`same => n,${mixMonitorWithRecorderId(`${recBase}.${recExt}`, flags, '${RECORDER_ID}')}`);
  } else {
    lines.push('same => n,Set(__safeclid=${FILTER(0-9+,${CALLERID(num)})})');
    lines.push('same => n,Set(__fname=${STRFTIME(${EPOCH},,%Y%m%d%H%M%S)}-${safeclid}-${EXTEN})');
    if (input.recordStereo) lines.push('same => n,Set(__REC_STEREO=1)');
    if (!input.hangupWebhook) {
      lines.push(`same => n,Set(__monopt=${buildFfmpegPostprocess(recBase, input.recordStereo)})`);
      lines.push(`same => n,Set(CDR(record)=${rpath}/\${path}/\${fname})`);
      lines.push(`same => n,MixMonitor(${recBase}.${recExt},${flags},\${monopt})`);
    } else {
      lines.push(`same => n,Set(CDR(record)=${rpath}/\${path}/\${fname})`);
      lines.push(`same => n,MixMonitor(${recBase}.${recExt},${flags})`);
    }
  }
  if (input.hangupWebhook || input.durable || Boolean(input.analyticsProjectId)) {
    const hangupContext = input.hangupContext ?? 'krsk-hangup-handler';
    lines.push(`same => n,Set(CHANNEL(hangup_handler_push)=${hangupContext},s,1)`);
  }
  return lines;
}

/** Isolated generated-route context for the test Asterisk (same MixMonitor shape as `generateRouteDialplan`). */
export function generatedDurableLabDialplan(vpbxUserUid = 8): string {
  const hangupContext = 'krasterisk-ai-generated-hangup';
  const recording = recordingDialplanLines({
    vpbxUserUid,
    durable: true,
    recordStereo: false,
    recordAll: true,
    hangupWebhook: false,
    hangupContext,
  });
  return [
    '; generated by route-recording.util generatedDurableLabDialplan — DURABLE_CAPTURE MixMonitor',
    '[krasterisk-ai-generated]',
    'exten => s,1,NoOp(Krasterisk generated-route MixMonitor lab)',
    'same => n,Answer()',
    `same => n,Set(CDR(vpbx_user_uid)=${vpbxUserUid})`,
    ...recording,
    'same => n,Playback(demo-thanks)',
    'same => n,Wait(2)',
    'same => n,Hangup()',
    '',
    `[${hangupContext}]`,
    'exten => s,1,NoOp(generated durable hangup)',
    'same => n,ExecIf($["${RECORDER_ID}" != ""]?StopMixMonitor(${RECORDER_ID}))',
    'same => n,Return()',
    '',
  ].join('\n');
}

/** ffmpeg command for MixMonitor postprocess (mono WAV → MP3). */
export function buildMonoFfmpegPostprocess(basePath: string): string {
  return `nice -n 10 /usr/bin/ffmpeg -y -i ${basePath}.wav -codec:a libmp3lame -b:a 32k -ar 8000 -ac 1 ${basePath}.mp3 -loglevel quiet && rm -f ${basePath}.wav`;
}

/** ffmpeg command for MixMonitor postprocess (stereo RAW → stereo MP3). */
export function buildStereoFfmpegPostprocess(basePath: string): string {
  return `nice -n 10 /usr/bin/ffmpeg -y -f s16le -ar 8000 -ac 2 -i ${basePath}.raw -codec:a libmp3lame -b:a 64k -ar 8000 -ac 2 ${basePath}.mp3 -loglevel quiet && rm -f ${basePath}.raw`;
}

export function buildFfmpegPostprocess(basePath: string, stereo: boolean): string {
  return stereo ? buildStereoFfmpegPostprocess(basePath) : buildMonoFfmpegPostprocess(basePath);
}
