CREATE TABLE IF NOT EXISTS ivrs (
  uid INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL DEFAULT '',
  exten VARCHAR(255) NOT NULL DEFAULT '',
  timeout VARCHAR(255),
  max_count INT NOT NULL DEFAULT 0,
  active TINYINT NOT NULL DEFAULT 1,
  direct_dial TINYINT NOT NULL DEFAULT 1,
  prompts JSON,
  menu_items JSON,
  user_uid INT NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
