-- AI-01-C2 neutral schema extracted from reviewed PostgreSQL 0001.
DO $$ BEGIN IF current_setting('server_encoding') <> 'UTF8' THEN RAISE EXCEPTION 'Krasterisk requires UTF8 database encoding'; END IF; END $$;

CREATE TYPE "enum_cc_ai_providers_kind" AS ENUM ('online', 'local', 'custom');
CREATE TYPE "enum_cc_ai_providers_auth_type" AS ENUM ('bearer', 'api_key_header', 'none', 'custom');
CREATE TYPE "enum_modules_registry_category" AS ENUM ('pbx', 'calls', 'analytics', 'integrations', 'admin');
CREATE TYPE "enum_tenant_modules_status" AS ENUM ('active', 'inactive', 'trial', 'expired');
CREATE TYPE "enum_tenant_modules_billing_cycle" AS ENUM ('monthly', 'yearly', 'lifetime');
CREATE TYPE "enum_tenants_status" AS ENUM ('trial', 'active', 'suspended', 'cancelled');
CREATE TYPE "enum_hub_modules_kind" AS ENUM ('base', 'market');

CREATE TABLE "users" (
  "uniqueid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "login" VARCHAR(255),
  "name" VARCHAR(255),
  "passwd" VARCHAR(255),
  "email" VARCHAR(255),
  "exten" VARCHAR(255),
  "level" INTEGER DEFAULT 2,
  "role" INTEGER,
  "numbers_id" INTEGER,
  "permit_extens" VARCHAR(255),
  "listbook_edit" INTEGER DEFAULT 0,
  "oper_chanspy" INTEGER DEFAULT 0,
  "outbound_posttime" INTEGER DEFAULT 0,
  "suspension_time" INTEGER DEFAULT 0,
  "inactive_time" INTEGER DEFAULT 0,
  "vpbx_user_uid" INTEGER DEFAULT 0,
  "activationCode" VARCHAR(255),
  "activationExpires" BIGINT,
  "isActivated" BOOLEAN DEFAULT false,
  "avatar" VARCHAR(255),
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("uniqueid")
);

CREATE TABLE "user_sessions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "user_id" INTEGER NOT NULL,
  "refreshToken" VARCHAR(512) NOT NULL,
  "userAgent" TEXT,
  "ipAddress" VARCHAR(45),
  "expiresAt" BIGINT NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "tenants" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "uid" VARCHAR(36) NOT NULL,
  "name" VARCHAR(255) NOT NULL,
  "slug" VARCHAR(128),
  "owner_user_id" INTEGER NOT NULL,
  "vpbx_user_uid" INTEGER NOT NULL,
  "status" "enum_tenants_status" DEFAULT 'trial',
  "trial_ends_at" TIMESTAMP WITH TIME ZONE,
  "email" VARCHAR(255),
  "phone" VARCHAR(32),
  "company_inn" VARCHAR(32),
  "max_extensions" INTEGER DEFAULT 10,
  "max_trunks" INTEGER DEFAULT 2,
  "max_queues" INTEGER DEFAULT 3,
  "created_by" INTEGER,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "action_logs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "user_id" INTEGER NOT NULL,
  "action" VARCHAR(64) NOT NULL,
  "entity_type" VARCHAR(64) NOT NULL,
  "entity_id" INTEGER,
  "details" TEXT,
  "vpbx_user_uid" INTEGER NOT NULL,
  "status" VARCHAR(16) NOT NULL DEFAULT 'success',
  "created_at" TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY ("id")
);

CREATE TABLE "roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(255),
  "role" TEXT,
  "comment" VARCHAR(255),
  "vpbx_user_uid" INTEGER DEFAULT 0,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "modules_registry" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "code" VARCHAR(64) NOT NULL UNIQUE,
  "name" VARCHAR(128) NOT NULL,
  "description" TEXT,
  "version" VARCHAR(16) DEFAULT '1.0.0',
  "category" "enum_modules_registry_category" DEFAULT 'pbx',
  "is_core" BOOLEAN DEFAULT false,
  "is_paid" BOOLEAN DEFAULT false,
  "price_monthly" DECIMAL(10,2) DEFAULT 0,
  "is_published" BOOLEAN DEFAULT true,
  "requires_cloud" BOOLEAN DEFAULT false,
  "dependencies" JSON,
  "created_at" TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY ("id")
);

CREATE TABLE "tenant_modules" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" INTEGER NOT NULL,
  "module_code" VARCHAR(64) NOT NULL,
  "status" "enum_tenant_modules_status" DEFAULT 'active',
  "activated_at" TIMESTAMP WITH TIME ZONE,
  "expires_at" TIMESTAMP WITH TIME ZONE,
  "billing_cycle" "enum_tenant_modules_billing_cycle" DEFAULT 'monthly',
  "last_billed_at" TIMESTAMP WITH TIME ZONE,
  "config" JSON,
  PRIMARY KEY ("id")
);

CREATE TABLE "cc_ai_providers" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(128) NOT NULL,
  "kind" "enum_cc_ai_providers_kind" NOT NULL,
  "vendor" VARCHAR(32) NOT NULL,
  "endpoint" VARCHAR(512) NOT NULL,
  "auth_type" "enum_cc_ai_providers_auth_type" DEFAULT 'bearer',
  "encrypted_api_key" TEXT,
  "capabilities" JSON NOT NULL,
  "defaults" JSON,
  "pricing" JSON NOT NULL,
  "enabled" BOOLEAN NOT NULL DEFAULT true,
  "vpbx_user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);

CREATE TABLE "cloud_settings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "key" VARCHAR(128) NOT NULL UNIQUE,
  "value" TEXT,
  "description" VARCHAR(255),
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "hub_modules" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "code" VARCHAR(64) NOT NULL UNIQUE,
  "name" VARCHAR(128) NOT NULL,
  "kind" "enum_hub_modules_kind" NOT NULL DEFAULT 'base',
  "sort_order" INTEGER DEFAULT 0,
  "requires_cloud" BOOLEAN DEFAULT false,
  PRIMARY KEY ("id")
);

CREATE TABLE "hub_module_pages" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "hub_code" VARCHAR(64) NOT NULL,
  "page_code" VARCHAR(64) NOT NULL,
  "path" VARCHAR(255),
  "sort_order" INTEGER DEFAULT 0,
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "uq_hub_module_page" ON "hub_module_pages" ("hub_code", "page_code");
CREATE INDEX "idx_hub_module_pages_hub" ON "hub_module_pages" ("hub_code");
CREATE UNIQUE INDEX "uq_hub_modules_code" ON "hub_modules" ("code");
CREATE UNIQUE INDEX "uq_tenant_module" ON "tenant_modules" ("tenant_id", "module_code");
CREATE INDEX "idx_tm_tenant" ON "tenant_modules" ("tenant_id");

ALTER TABLE "hub_module_pages" ADD FOREIGN KEY ("hub_code") REFERENCES "hub_modules" ("code") ON DELETE NO ACTION ON UPDATE CASCADE;
