-- DB-02 PostgreSQL baseline: reviewed schema snapshot of the 112 AppModule models.
-- Empty UTF8 database only. Timestamps are UTC instants (TIMESTAMPTZ).
-- Asterisk queue_log/CEL writer and legacy data adoption belong to DB-03.
-- Source MySQL 0001 SHA-256: 8c18e47d94da3c3aeca3807eb44dbd0280433c1dedf96bef36470203d699543d
DO $$ BEGIN IF current_setting('server_encoding') <> 'UTF8' THEN RAISE EXCEPTION 'Krasterisk requires UTF8 database encoding'; END IF; END $$;

CREATE TYPE "enum_billing_transactions_type" AS ENUM ('deposit', 'charge', 'refund', 'correction');
CREATE TYPE "enum_billing_transactions_sbis_status" AS ENUM ('pending', 'done', 'failed');
CREATE TYPE "enum_call_group_members_member_type" AS ENUM ('internal', 'external');
CREATE TYPE "enum_call_groups_strategy" AS ENUM ('ringall', 'hunt', 'memoryhunt', 'random');
CREATE TYPE "enum_cc_agent_events_event_type" AS ENUM ('LOGIN', 'LOGOUT', 'READY', 'PAUSE', 'CALL_START', 'CALL_END', 'WRAPUP_START', 'WRAPUP_END', 'HOLD', 'UNHOLD', 'DIALING', 'CONSULT', 'ACW');
CREATE TYPE "enum_cc_ai_agents_mode" AS ENUM ('realtime', 'cascade');
CREATE TYPE "enum_cc_ai_agents_channel_kind" AS ENUM ('local', 'pjsip');
CREATE TYPE "enum_cc_ai_audit_log_status" AS ENUM ('ok', 'error', 'rate_limited', 'denied');
CREATE TYPE "enum_cc_ai_cdr_pipeline_mode" AS ENUM ('realtime', 'cascade');
CREATE TYPE "enum_cc_ai_invoices_status" AS ENUM ('draft', 'issued', 'paid', 'void');
CREATE TYPE "enum_cc_ai_providers_kind" AS ENUM ('online', 'local', 'custom');
CREATE TYPE "enum_cc_ai_providers_auth_type" AS ENUM ('bearer', 'api_key_header', 'none', 'custom');
CREATE TYPE "enum_cc_card_data_status" AS ENUM ('draft', 'saved', 'missed', 'callback_done');
CREATE TYPE "enum_cc_card_fields_field_type" AS ENUM ('text', 'textarea', 'phone', 'email', 'select', 'multi_select', 'date', 'datetime', 'number', 'checkbox', 'phonebook_lookup', 'divider', 'heading', 'readonly');
CREATE TYPE "enum_cc_card_fields_width" AS ENUM ('full', 'half');
CREATE TYPE "enum_cc_card_templates_auto_open_on" AS ENUM ('answer', 'ring', 'manual');
CREATE TYPE "enum_cc_chat_channels_type" AS ENUM ('direct', 'group', 'broadcast_all', 'broadcast_queue');
CREATE TYPE "enum_cc_chat_messages_channel_type" AS ENUM ('direct', 'group', 'broadcast_all', 'broadcast_queue');
CREATE TYPE "enum_cc_queue_calls_disposition" AS ENUM ('answered', 'abandoned', 'transferred', 'timeout', 'other');
CREATE TYPE "enum_cc_report_schedules_format" AS ENUM ('csv', 'xlsx');
CREATE TYPE "enum_cc_report_schedules_period_preset" AS ENUM ('today', 'yesterday', 'last-7-days', 'last-30-days', 'previous-month');
CREATE TYPE "enum_cc_report_schedules_frequency" AS ENUM ('daily', 'weekly', 'monthly');
CREATE TYPE "enum_conference_guest_tokens_kind" AS ENUM ('shared_link', 'named_invite');
CREATE TYPE "enum_conference_meeting_participants_role" AS ENUM ('owner', 'moderator', 'participant');
CREATE TYPE "enum_conference_room_moderators_role" AS ENUM ('owner', 'moderator');
CREATE TYPE "enum_conference_rooms_kind" AS ENUM ('permanent', 'ephemeral');
CREATE TYPE "enum_conference_rooms_entry_strictness" AS ENUM ('token_name', 'token_name_pin', 'token_name_pin_moderator');
CREATE TYPE "enum_conference_rooms_record_mode" AS ENUM ('off', 'auto', 'button', 'both');
CREATE TYPE "enum_conference_rooms_invite_external_scope" AS ENUM ('owner', 'moderator', 'anyone');
CREATE TYPE "enum_hub_modules_kind" AS ENUM ('base', 'market');
CREATE TYPE "enum_modules_registry_category" AS ENUM ('pbx', 'calls', 'analytics', 'integrations', 'admin');
CREATE TYPE "enum_musiconhold_mode" AS ENUM ('custom', 'files', 'mp3nb', 'quietmp3nb', 'quietmp3', 'playlist');
CREATE TYPE "enum_notification_integrations_channel" AS ENUM ('telegram', 'email', 'whatsapp', 'webhook', 'max', 'vk');
CREATE TYPE "enum_ps_endpoint_id_ips_srv_lookups" AS ENUM ('yes', 'no');
CREATE TYPE "enum_ps_registrations_auth_rejection_permanent" AS ENUM ('yes', 'no');
CREATE TYPE "enum_ps_registrations_support_path" AS ENUM ('yes', 'no');
CREATE TYPE "enum_ps_registrations_line" AS ENUM ('yes', 'no');
CREATE TYPE "enum_tenant_modules_status" AS ENUM ('active', 'inactive', 'trial', 'expired');
CREATE TYPE "enum_tenant_modules_billing_cycle" AS ENUM ('monthly', 'yearly', 'lifetime');
CREATE TYPE "enum_tenants_status" AS ENUM ('trial', 'active', 'suspended', 'cancelled');

CREATE TABLE "ac_attempts" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "vpbx_user_uid" INTEGER NOT NULL,
  "task_uid" INTEGER NOT NULL,
  "campaign_uid" INTEGER NOT NULL,
  "attempt_no" INTEGER NOT NULL DEFAULT 1,
  "started_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "answered_at" TIMESTAMP WITH TIME ZONE,
  "ended_at" TIMESTAMP WITH TIME ZONE,
  "duration" INTEGER NOT NULL DEFAULT 0,
  "billsec" INTEGER NOT NULL DEFAULT 0,
  "disposition" VARCHAR(24) NOT NULL DEFAULT 'dialing',
  "hangup_cause" VARCHAR(64),
  "trunk_id" VARCHAR(128),
  "caller_id" VARCHAR(64),
  "channel_id" VARCHAR(128),
  "uniqueid" VARCHAR(64),
  "linkedid" VARCHAR(64),
  "amd_result" VARCHAR(32),
  "queue_name" VARCHAR(128),
  "agent_interface" VARCHAR(128),
  "talk_sec" INTEGER NOT NULL DEFAULT 0,
  "scenario_result" JSON,
  PRIMARY KEY ("uid")
);
CREATE TABLE "ac_base_fields" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "base_uid" INTEGER NOT NULL,
  "key" VARCHAR(64) NOT NULL,
  "label" VARCHAR(255) NOT NULL,
  "type" VARCHAR(16) NOT NULL,
  "required" BOOLEAN NOT NULL DEFAULT false,
  "position" INTEGER NOT NULL DEFAULT 0,
  "is_phone" BOOLEAN NOT NULL DEFAULT false,
  "var_name" VARCHAR(64) NOT NULL DEFAULT '',
  "enum_values" JSON,
  PRIMARY KEY ("uid")
);
CREATE TABLE "ac_bases" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "vpbx_user_uid" INTEGER NOT NULL,
  "name" VARCHAR(255) NOT NULL,
  "description" VARCHAR(512) NOT NULL DEFAULT '',
  "dedup_policy" VARCHAR(16) NOT NULL DEFAULT 'phone',
  "phone_normalization" VARCHAR(16) NOT NULL DEFAULT 'ru_8_to_7',
  "revision" INTEGER NOT NULL DEFAULT 0,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("uid")
);
CREATE TABLE "ac_campaigns" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "vpbx_user_uid" INTEGER NOT NULL,
  "name" VARCHAR(255) NOT NULL,
  "status" VARCHAR(16) NOT NULL DEFAULT 'draft',
  "dial_mode" VARCHAR(16) NOT NULL DEFAULT 'progressive',
  "base_uid" INTEGER NOT NULL,
  "pacing" JSON NOT NULL,
  "retry" JSON NOT NULL,
  "trunk_pool" JSON NOT NULL,
  "cid_policy" JSON NOT NULL,
  "queue_names" JSON NOT NULL,
  "scenario_actions" JSON NOT NULL,
  "amd" JSON NOT NULL,
  "success_min_sec" INTEGER NOT NULL DEFAULT 15,
  "dial_timeout_sec" INTEGER NOT NULL DEFAULT 45,
  "revision" INTEGER NOT NULL DEFAULT 0,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("uid")
);
CREATE TABLE "ac_contact_phones" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "contact_uid" INTEGER NOT NULL,
  "base_uid" INTEGER NOT NULL,
  "raw" VARCHAR(64) NOT NULL,
  "normalized" VARCHAR(64) NOT NULL,
  "position" INTEGER NOT NULL DEFAULT 0,
  "is_primary" BOOLEAN NOT NULL DEFAULT false,
  "tz_offset_min" INTEGER NOT NULL DEFAULT 180,
  PRIMARY KEY ("uid")
);
CREATE TABLE "ac_contacts" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "base_uid" INTEGER NOT NULL,
  "vpbx_user_uid" INTEGER NOT NULL,
  "external_id" VARCHAR(128),
  "values" JSON NOT NULL,
  "comment" VARCHAR(512) NOT NULL DEFAULT '',
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("uid")
);
CREATE TABLE "ac_daily_campaign_stats" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "vpbx_user_uid" INTEGER NOT NULL,
  "campaign_uid" INTEGER NOT NULL,
  "day" DATE NOT NULL,
  "dials" INTEGER NOT NULL DEFAULT 0,
  "answered" INTEGER NOT NULL DEFAULT 0,
  "success" INTEGER NOT NULL DEFAULT 0,
  "short" INTEGER NOT NULL DEFAULT 0,
  "no_answer" INTEGER NOT NULL DEFAULT 0,
  "busy" INTEGER NOT NULL DEFAULT 0,
  "amd" INTEGER NOT NULL DEFAULT 0,
  "failed" INTEGER NOT NULL DEFAULT 0,
  "talk_sec_sum" INTEGER NOT NULL DEFAULT 0,
  "billsec_sum" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "ac_dnc" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "vpbx_user_uid" INTEGER NOT NULL,
  "scope" VARCHAR(16) NOT NULL DEFAULT 'global',
  "scope_uid" INTEGER,
  "normalized_phone" VARCHAR(64) NOT NULL,
  "reason" VARCHAR(255) NOT NULL DEFAULT '',
  "source" VARCHAR(64) NOT NULL DEFAULT 'manual',
  "expires_at" TIMESTAMP WITH TIME ZONE,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("uid")
);
CREATE TABLE "ac_import_profiles" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "base_uid" INTEGER NOT NULL,
  "vpbx_user_uid" INTEGER NOT NULL,
  "name" VARCHAR(255) NOT NULL,
  "source" VARCHAR(8) NOT NULL DEFAULT 'csv',
  "delimiter" VARCHAR(4) NOT NULL DEFAULT ';',
  "encoding" VARCHAR(32) NOT NULL DEFAULT 'utf-8',
  "has_header" BOOLEAN NOT NULL DEFAULT true,
  "column_map" JSON NOT NULL,
  "dedup_policy" VARCHAR(16) NOT NULL DEFAULT 'phone',
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("uid")
);
CREATE TABLE "ac_import_runs" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "base_uid" INTEGER NOT NULL,
  "vpbx_user_uid" INTEGER NOT NULL,
  "profile_uid" INTEGER,
  "filename" VARCHAR(512) NOT NULL DEFAULT '',
  "total_rows" INTEGER NOT NULL DEFAULT 0,
  "imported" INTEGER NOT NULL DEFAULT 0,
  "skipped" INTEGER NOT NULL DEFAULT 0,
  "errors" JSON,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("uid")
);
CREATE TABLE "ac_schedules" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "campaign_uid" INTEGER NOT NULL,
  "kind" VARCHAR(16) NOT NULL DEFAULT 'weekly',
  "weekday" SMALLINT,
  "time_from" VARCHAR(5) NOT NULL DEFAULT '09:00',
  "time_to" VARCHAR(5) NOT NULL DEFAULT '21:00',
  "timezone" VARCHAR(64) NOT NULL DEFAULT 'Europe/Moscow',
  "date_from" DATE,
  "date_to" DATE,
  "enabled" BOOLEAN NOT NULL DEFAULT true,
  PRIMARY KEY ("uid")
);
CREATE TABLE "ac_tasks" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "vpbx_user_uid" INTEGER NOT NULL,
  "campaign_uid" INTEGER NOT NULL,
  "contact_uid" INTEGER NOT NULL,
  "phone_uid" INTEGER NOT NULL,
  "status" VARCHAR(16) NOT NULL DEFAULT 'pending',
  "attempt_count" INTEGER NOT NULL DEFAULT 0,
  "next_attempt_at" TIMESTAMP WITH TIME ZONE,
  "last_disposition" VARCHAR(24) NOT NULL DEFAULT 'new',
  "last_cause" VARCHAR(64),
  "leased_by" VARCHAR(64),
  "leased_at" TIMESTAMP WITH TIME ZONE,
  "priority" INTEGER NOT NULL DEFAULT 0,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("uid")
);
CREATE TABLE "action_logs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "user_id" INTEGER NOT NULL,
  "action" VARCHAR(64) NOT NULL,
  "entity_type" VARCHAR(64) NOT NULL,
  "entity_id" INTEGER,
  "details" TEXT,
  "vpbx_user_uid" INTEGER NOT NULL,
  "status" VARCHAR(16) NOT NULL DEFAULT 'success',
  "created_at" TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY ("id")
);
CREATE TABLE "ai_agent_proposals" (
  "proposal_id" CHAR(36),
  "thread_uid" INTEGER NOT NULL,
  "vpbx_user_uid" INTEGER NOT NULL,
  "user_uid" INTEGER NOT NULL,
  "entity_type" VARCHAR(64) NOT NULL,
  "entity_label" VARCHAR(255) NOT NULL,
  "summary" JSON NOT NULL,
  "before_json" JSON,
  "after_json" JSON,
  "apply_payload" JSON NOT NULL,
  "includes_dialplan_reload" BOOLEAN NOT NULL DEFAULT false,
  "status" VARCHAR(16) NOT NULL DEFAULT 'pending',
  "error" TEXT,
  "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "applied_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("proposal_id")
);
CREATE TABLE "ai_agent_thread_messages" (
  "uid" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "thread_uid" INTEGER NOT NULL,
  "vpbx_user_uid" INTEGER NOT NULL,
  "role" VARCHAR(16) NOT NULL,
  "content" TEXT,
  "tool_name" VARCHAR(128) DEFAULT NULL,
  "tool_calls" JSON,
  "proposal_id" CHAR(36) DEFAULT NULL,
  "tool_call_id" VARCHAR(128) DEFAULT NULL,
  "provider_model" VARCHAR(128) DEFAULT NULL,
  "close_kind" VARCHAR(16) DEFAULT NULL,
  "visibility" VARCHAR(16) NOT NULL DEFAULT 'public',
  "reasoning" TEXT,
  "tokens_in" INTEGER NOT NULL DEFAULT 0,
  "tokens_out" INTEGER NOT NULL DEFAULT 0,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("uid")
);
CREATE TABLE "ai_agent_threads" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "vpbx_user_uid" INTEGER NOT NULL,
  "user_uid" INTEGER NOT NULL,
  "title" VARCHAR(255) NOT NULL DEFAULT '',
  "status" VARCHAR(16) NOT NULL DEFAULT 'active',
  "provider_uid" INTEGER DEFAULT NULL,
  "tokens_in" INTEGER NOT NULL DEFAULT 0,
  "tokens_out" INTEGER NOT NULL DEFAULT 0,
  "brief_json" JSON,
  "brief_version" INTEGER NOT NULL DEFAULT 0,
  "brief_updated_through_message_uid" BIGINT DEFAULT NULL,
  "last_message_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("uid")
);
CREATE TABLE "ai_agent_workflow_steps" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "workflow_uid" INTEGER NOT NULL,
  "step_key" VARCHAR(64) NOT NULL,
  "step_index" INTEGER NOT NULL DEFAULT 0,
  "tool" VARCHAR(128) NOT NULL,
  "entity_type" VARCHAR(64) NOT NULL DEFAULT '',
  "entity_label" VARCHAR(255) NOT NULL DEFAULT '',
  "depends_on" JSON NOT NULL,
  "canonical_args" JSON NOT NULL,
  "schema_version" VARCHAR(64) NOT NULL,
  "before_json" JSON,
  "after_json" JSON,
  "result_json" JSON,
  "status" VARCHAR(16) NOT NULL DEFAULT 'pending',
  "attempts" INTEGER NOT NULL DEFAULT 0,
  "error" TEXT,
  "requires_secure_input" BOOLEAN NOT NULL DEFAULT false,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("uid")
);
CREATE TABLE "ai_agent_workflows" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "workflow_id" CHAR(36) NOT NULL UNIQUE,
  "thread_uid" INTEGER NOT NULL,
  "vpbx_user_uid" INTEGER NOT NULL,
  "user_uid" INTEGER NOT NULL,
  "brief_version" INTEGER NOT NULL DEFAULT 0,
  "title" VARCHAR(255) NOT NULL DEFAULT '',
  "summary" JSON NOT NULL,
  "status" VARCHAR(16) NOT NULL DEFAULT 'pending',
  "error" TEXT,
  "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "applied_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("uid")
);
CREATE TABLE "ai_chat_settings" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "user_uid" INTEGER NOT NULL UNIQUE,
  "confirm_destructive" SMALLINT NOT NULL DEFAULT 0,
  "settings" JSON,
  "created_at" TIMESTAMP WITH TIME ZONE,
  "updated_at" TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY ("uid")
);
CREATE TABLE "billing_balances" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" INTEGER NOT NULL UNIQUE,
  "balance_kopecks" BIGINT DEFAULT 0,
  "credit_limit_kopecks" BIGINT DEFAULT 0,
  "currency" VARCHAR(3) DEFAULT 'RUB',
  "is_blocked" BOOLEAN DEFAULT false,
  "blocked_at" TIMESTAMP WITH TIME ZONE,
  "updated_at" TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY ("id")
);
CREATE TABLE "billing_transactions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" INTEGER NOT NULL,
  "type" "enum_billing_transactions_type" NOT NULL,
  "amount_kopecks" BIGINT NOT NULL,
  "balance_before" BIGINT NOT NULL,
  "balance_after" BIGINT NOT NULL,
  "description" VARCHAR(512),
  "module_code" VARCHAR(64),
  "performed_by" INTEGER,
  "external_id" VARCHAR(128) UNIQUE,
  "doc_number" INTEGER,
  "sbis_id" VARCHAR(128),
  "sbis_url" TEXT,
  "sbis_status" "enum_billing_transactions_sbis_status",
  "sbis_doc_num" VARCHAR(64),
  "created_at" TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY ("id")
);
CREATE TABLE "call_group_members" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "call_group_uid" INTEGER NOT NULL,
  "member_type" "enum_call_group_members_member_type" NOT NULL,
  "value" VARCHAR(128) NOT NULL,
  "position" INTEGER NOT NULL DEFAULT 0,
  "ring_time" INTEGER NOT NULL DEFAULT 20,
  "vpbx_user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "call_groups" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(128) NOT NULL,
  "exten" VARCHAR(8) NOT NULL,
  "strategy" "enum_call_groups_strategy" NOT NULL,
  "ring_time" INTEGER NOT NULL DEFAULT 25,
  "external_context" VARCHAR(128),
  "cid_prefix" VARCHAR(64),
  "vpbx_user_uid" INTEGER NOT NULL DEFAULT 0,
  "confirm_external" BOOLEAN NOT NULL DEFAULT false,
  "confirm_digit" VARCHAR(1) NOT NULL DEFAULT '1',
  "skip_busy" BOOLEAN NOT NULL DEFAULT false,
  "greeting_prompt" VARCHAR(128),
  "moh_class" VARCHAR(64),
  "use_moh_instead_of_ringback" BOOLEAN NOT NULL DEFAULT false,
  "dial_options" VARCHAR(64) NOT NULL DEFAULT 'tT',
  PRIMARY KEY ("uid")
);
CREATE TABLE "cc_agent_events" (
  "uid" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "session_id" INTEGER NOT NULL,
  "user_id" INTEGER NOT NULL,
  "event_type" "enum_cc_agent_events_event_type" NOT NULL,
  "reason" VARCHAR(128) DEFAULT '',
  "call_uniqueid" VARCHAR(64) DEFAULT '',
  "caller_id" VARCHAR(32) DEFAULT '',
  "queue_name" VARCHAR(64) DEFAULT '',
  "duration" INTEGER DEFAULT 0,
  "created_at" TIMESTAMP WITH TIME ZONE,
  "vpbx_user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "cc_agent_queues" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "user_id" INTEGER NOT NULL,
  "agent_interface" VARCHAR(64) NOT NULL,
  "queue_name" VARCHAR(64) NOT NULL,
  "penalty" INTEGER DEFAULT 0,
  "user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "cc_agent_sessions" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "user_id" INTEGER NOT NULL,
  "agent_interface" VARCHAR(64) NOT NULL,
  "login_time" TIMESTAMP WITH TIME ZONE,
  "logout_time" TIMESTAMP WITH TIME ZONE,
  "total_calls" INTEGER DEFAULT 0,
  "total_talk_time" INTEGER DEFAULT 0,
  "total_pause_time" INTEGER DEFAULT 0,
  "total_idle_time" INTEGER DEFAULT 0,
  "last_status" VARCHAR(32),
  "last_status_at" TIMESTAMP WITH TIME ZONE,
  "pause_reason" VARCHAR(128),
  "last_status_origin" VARCHAR(16),
  "queues_snapshot" JSON,
  "softphone_mode" VARCHAR(16),
  "panel_seen_at" TIMESTAMP WITH TIME ZONE,
  "close_reason" VARCHAR(32),
  "vpbx_user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "cc_ai_agents" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(128) NOT NULL,
  "unique_id" VARCHAR(64) NOT NULL,
  "mode" "enum_cc_ai_agents_mode" NOT NULL DEFAULT 'realtime',
  "voice" VARCHAR(64) DEFAULT '',
  "greeting" TEXT,
  "instruction" TEXT,
  "model_profile_id" INTEGER,
  "stt_profile_id" INTEGER,
  "tts_profile_id" INTEGER,
  "vad_config" JSON,
  "toolset_id" INTEGER,
  "channel_kind" "enum_cc_ai_agents_channel_kind" NOT NULL DEFAULT 'local',
  "enabled" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "vpbx_user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "cc_ai_audit_log" (
  "uid" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "call_uniqueid" VARCHAR(64),
  "thread_uid" INTEGER DEFAULT NULL,
  "agent_uid" INTEGER,
  "tool_name" VARCHAR(128) NOT NULL,
  "args" JSON,
  "result" JSON,
  "duration_ms" INTEGER DEFAULT 0,
  "status" "enum_cc_ai_audit_log_status" NOT NULL DEFAULT 'ok',
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "vpbx_user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "cc_ai_billing" (
  "uid" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "period" DATE NOT NULL,
  "total_calls" INTEGER NOT NULL DEFAULT 0,
  "total_tokens_in" BIGINT NOT NULL DEFAULT 0,
  "total_tokens_out" BIGINT NOT NULL DEFAULT 0,
  "total_audio_seconds" BIGINT NOT NULL DEFAULT 0,
  "total_cost" DECIMAL(14,4) NOT NULL DEFAULT 0,
  "currency" VARCHAR(8) NOT NULL DEFAULT 'USD',
  "vpbx_user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "cc_ai_cdr" (
  "uid" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "call_uniqueid" VARCHAR(64) NOT NULL,
  "agent_uid" INTEGER NOT NULL,
  "provider_uid" INTEGER,
  "queue" VARCHAR(64) DEFAULT '',
  "pipeline_mode" "enum_cc_ai_cdr_pipeline_mode" NOT NULL,
  "started_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "ended_at" TIMESTAMP WITH TIME ZONE,
  "duration_sec" INTEGER NOT NULL DEFAULT 0,
  "tokens_in" INTEGER NOT NULL DEFAULT 0,
  "tokens_out" INTEGER NOT NULL DEFAULT 0,
  "audio_seconds" INTEGER NOT NULL DEFAULT 0,
  "tool_calls" JSON,
  "cost_input" DECIMAL(10,4) NOT NULL DEFAULT 0,
  "cost_output" DECIMAL(10,4) NOT NULL DEFAULT 0,
  "cost_audio" DECIMAL(10,4) NOT NULL DEFAULT 0,
  "cost_total" DECIMAL(10,4) NOT NULL DEFAULT 0,
  "currency" VARCHAR(8) NOT NULL DEFAULT 'USD',
  "recording_ref" VARCHAR(255) DEFAULT '',
  "transcript_ref" VARCHAR(255) DEFAULT '',
  "vpbx_user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "cc_ai_invoices" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "invoice_number" VARCHAR(64) NOT NULL,
  "period_from" DATE NOT NULL,
  "period_to" DATE NOT NULL,
  "total_amount" DECIMAL(14,4) NOT NULL DEFAULT 0,
  "currency" VARCHAR(8) NOT NULL DEFAULT 'USD',
  "status" "enum_cc_ai_invoices_status" NOT NULL DEFAULT 'draft',
  "pdf_ref" VARCHAR(512),
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "vpbx_user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "cc_ai_providers" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(128) NOT NULL,
  "kind" "enum_cc_ai_providers_kind" NOT NULL,
  "vendor" VARCHAR(32) NOT NULL,
  "endpoint" VARCHAR(512) NOT NULL,
  "auth_type" "enum_cc_ai_providers_auth_type" DEFAULT 'bearer',
  "encrypted_api_key" TEXT,
  "capabilities" JSON NOT NULL,
  "defaults" JSON,
  "pricing" JSON NOT NULL,
  "enabled" BOOLEAN NOT NULL DEFAULT true,
  "vpbx_user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "cc_ai_toolsets" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(128) NOT NULL,
  "description" TEXT,
  "tools" JSON NOT NULL,
  "vpbx_user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "cc_alert_config" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "integration_uid" INTEGER,
  "target" VARCHAR(255),
  "enabled" BOOLEAN NOT NULL DEFAULT false,
  "cooldown_sec" INTEGER NOT NULL DEFAULT 300,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "vpbx_user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "cc_callback_requests" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "vpbx_user_uid" INTEGER NOT NULL DEFAULT 0,
  "caller" VARCHAR(64) NOT NULL DEFAULT '',
  "route_uid" INTEGER,
  "queue_uid" INTEGER,
  "queue_name" VARCHAR(64),
  "step_id" VARCHAR(64),
  "uniqueid" VARCHAR(128),
  "status" VARCHAR(16) NOT NULL DEFAULT 'pending',
  "attempt_count" INTEGER NOT NULL DEFAULT 0,
  "max_attempts" INTEGER NOT NULL DEFAULT 3,
  "pause_minutes" INTEGER NOT NULL DEFAULT 30,
  "next_attempt_at" TIMESTAMP WITH TIME ZONE,
  "window_start" VARCHAR(5) NOT NULL DEFAULT '09:00',
  "window_end" VARCHAR(5) NOT NULL DEFAULT '21:00',
  "claimed_agent_uid" INTEGER,
  "source" VARCHAR(24) NOT NULL DEFAULT 'route_step',
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("uid")
);
CREATE TABLE "cc_card_data" (
  "uid" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "template_id" INTEGER NOT NULL,
  "call_uniqueid" VARCHAR(64) DEFAULT '',
  "caller_id" VARCHAR(32) DEFAULT '',
  "queue_name" VARCHAR(64) DEFAULT '',
  "agent_user_uid" INTEGER,
  "status" "enum_cc_card_data_status" NOT NULL DEFAULT 'saved',
  "field_values" JSON NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP WITH TIME ZONE,
  "vpbx_user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "cc_card_fields" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "template_id" INTEGER NOT NULL,
  "field_key" VARCHAR(64) NOT NULL,
  "field_type" "enum_cc_card_fields_field_type" NOT NULL,
  "label" VARCHAR(128) NOT NULL,
  "placeholder" VARCHAR(256) DEFAULT '',
  "is_required" BOOLEAN NOT NULL DEFAULT false,
  "default_value" VARCHAR(256) DEFAULT '',
  "options" JSON,
  "depends_on" VARCHAR(64),
  "depends_values" JSON,
  "sort_order" INTEGER NOT NULL DEFAULT 0,
  "width" "enum_cc_card_fields_width" NOT NULL DEFAULT 'full',
  "auto_populate" VARCHAR(64),
  "vpbx_user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "cc_card_templates" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(128) NOT NULL,
  "description" TEXT,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "auto_open_on" "enum_cc_card_templates_auto_open_on" NOT NULL DEFAULT 'answer',
  "auto_save_on_timeout" BOOLEAN NOT NULL DEFAULT true,
  "webhook_integration_uid" INTEGER DEFAULT NULL,
  "webhook_field_map" JSON,
  "queue_names" JSON,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP WITH TIME ZONE,
  "vpbx_user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "cc_chat_channels" (
  "uid" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "channel_key" VARCHAR(128) NOT NULL,
  "type" "enum_cc_chat_channels_type" NOT NULL,
  "name" VARCHAR(128),
  "member_user_ids" JSON,
  "queue_name" VARCHAR(64),
  "created_by" INTEGER NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "vpbx_user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "cc_chat_messages" (
  "uid" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "channel_key" VARCHAR(128) NOT NULL,
  "channel_type" "enum_cc_chat_messages_channel_type" NOT NULL,
  "sender_user_id" INTEGER NOT NULL,
  "sender_name" VARCHAR(128),
  "body" TEXT NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "vpbx_user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "cc_contacts" (
  "uid" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "vpbx_user_uid" INTEGER NOT NULL DEFAULT 0,
  "created_by" INTEGER NOT NULL,
  "name" VARCHAR(128) NOT NULL,
  "number" VARCHAR(64) NOT NULL,
  "note" VARCHAR(255) DEFAULT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("uid")
);
CREATE TABLE "cc_daily_agent_stats" (
  "uid" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "stat_date" DATE NOT NULL,
  "agent_interface" VARCHAR(64) NOT NULL,
  "agent_user_uid" INTEGER,
  "calls_handled" INTEGER NOT NULL DEFAULT 0,
  "total_talk_sec" INTEGER NOT NULL DEFAULT 0,
  "total_hold_sec" INTEGER NOT NULL DEFAULT 0,
  "total_wrapup_sec" INTEGER NOT NULL DEFAULT 0,
  "avg_handle_sec" INTEGER NOT NULL DEFAULT 0,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "vpbx_user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "cc_daily_queue_stats" (
  "uid" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "stat_date" DATE NOT NULL,
  "queue_name" VARCHAR(64) NOT NULL,
  "total_calls" INTEGER NOT NULL DEFAULT 0,
  "answered_calls" INTEGER NOT NULL DEFAULT 0,
  "abandoned_calls" INTEGER NOT NULL DEFAULT 0,
  "sla_met_calls" INTEGER NOT NULL DEFAULT 0,
  "avg_wait_sec" INTEGER NOT NULL DEFAULT 0,
  "avg_talk_sec" INTEGER NOT NULL DEFAULT 0,
  "avg_hold_sec" INTEGER NOT NULL DEFAULT 0,
  "max_wait_sec" INTEGER NOT NULL DEFAULT 0,
  "total_talk_sec" INTEGER NOT NULL DEFAULT 0,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "vpbx_user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "cc_display_tokens" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "token" VARCHAR(64) NOT NULL,
  "label" VARCHAR(128),
  "created_by" INTEGER,
  "expires_at" TIMESTAMP WITH TIME ZONE,
  "revoked_at" TIMESTAMP WITH TIME ZONE,
  "last_used_at" TIMESTAMP WITH TIME ZONE,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "vpbx_user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "cc_districts" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "territorial_zone" VARCHAR(128) NOT NULL,
  "district" VARCHAR(128) NOT NULL,
  "sort_order" INTEGER DEFAULT 0,
  "is_active" BOOLEAN DEFAULT true,
  PRIMARY KEY ("uid")
);
CREATE TABLE "cc_missed_calls" (
  "uid" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "call_uniqueid" VARCHAR(64) NOT NULL UNIQUE,
  "queue_name" VARCHAR(64) NOT NULL,
  "caller_id_num" VARCHAR(32) NOT NULL DEFAULT '',
  "caller_id_name" VARCHAR(128) DEFAULT '',
  "hold_time" INTEGER DEFAULT 0,
  "position" INTEGER DEFAULT 0,
  "called_back" BOOLEAN NOT NULL DEFAULT false,
  "called_back_by" INTEGER,
  "called_back_at" TIMESTAMP WITH TIME ZONE,
  "note" VARCHAR(255) DEFAULT '',
  "client_called_back" BOOLEAN NOT NULL DEFAULT false,
  "personal" BOOLEAN NOT NULL DEFAULT false,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "vpbx_user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "cc_operator_settings" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "operator_user_id" INTEGER NOT NULL,
  "pickup_enabled" BOOLEAN NOT NULL DEFAULT false,
  "auto_answer" BOOLEAN NOT NULL DEFAULT false,
  "auto_answer_zip_tone" BOOLEAN NOT NULL DEFAULT true,
  "wrapup_timeout" INTEGER NOT NULL DEFAULT 30,
  "wrapup_extend_step" INTEGER NOT NULL DEFAULT 30,
  "wrapup_autosave_draft" BOOLEAN NOT NULL DEFAULT true,
  "sound_incoming" BOOLEAN NOT NULL DEFAULT true,
  "sound_missed" BOOLEAN NOT NULL DEFAULT true,
  "notifications_enabled" BOOLEAN NOT NULL DEFAULT true,
  "volume" INTEGER NOT NULL DEFAULT 100,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "can_spy" BOOLEAN NOT NULL DEFAULT false,
  "spyable" BOOLEAN NOT NULL DEFAULT true,
  "click_to_call" BOOLEAN NOT NULL DEFAULT true,
  "customize_ui" BOOLEAN NOT NULL DEFAULT false,
  "spy_modes" JSON NOT NULL,
  "ui_visibility" JSON,
  "softphone_placement" VARCHAR(16) NOT NULL DEFAULT 'bottom-right',
  "notification_matrix" JSON,
  "supervised_agent_extens" JSON,
  "vpbx_user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "cc_pause_reasons" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(128) NOT NULL,
  "color" VARCHAR(7) DEFAULT '#f59e0b',
  "max_duration" INTEGER DEFAULT 0,
  "is_paid" BOOLEAN DEFAULT true,
  "sort_order" INTEGER DEFAULT 0,
  "vpbx_user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "cc_queue_calls" (
  "uid" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "call_uniqueid" VARCHAR(64) NOT NULL,
  "queue_name" VARCHAR(64) NOT NULL,
  "agent_interface" VARCHAR(64) DEFAULT '',
  "agent_user_uid" INTEGER,
  "caller_id_num" VARCHAR(32) NOT NULL DEFAULT '',
  "caller_id_name" VARCHAR(128) DEFAULT '',
  "enter_time" TIMESTAMP WITH TIME ZONE,
  "answer_time" TIMESTAMP WITH TIME ZONE,
  "end_time" TIMESTAMP WITH TIME ZONE,
  "wait_time" INTEGER NOT NULL DEFAULT 0,
  "talk_time" INTEGER NOT NULL DEFAULT 0,
  "hold_time" INTEGER NOT NULL DEFAULT 0,
  "wrapup_time" INTEGER NOT NULL DEFAULT 0,
  "disposition" "enum_cc_queue_calls_disposition" NOT NULL DEFAULT 'other',
  "transfer_destination" VARCHAR(64) DEFAULT '',
  "position" INTEGER NOT NULL DEFAULT 0,
  "direction" VARCHAR(16) NOT NULL DEFAULT 'inbound',
  "call_type" VARCHAR(32) DEFAULT '',
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "vpbx_user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "cc_report_schedules" (
  "uid" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(128) NOT NULL,
  "report_id" VARCHAR(32) NOT NULL,
  "format" "enum_cc_report_schedules_format" NOT NULL DEFAULT 'xlsx',
  "period_preset" "enum_cc_report_schedules_period_preset" NOT NULL DEFAULT 'yesterday',
  "filters" JSON,
  "frequency" "enum_cc_report_schedules_frequency" NOT NULL DEFAULT 'daily',
  "hour" INTEGER NOT NULL DEFAULT 8,
  "minute" INTEGER NOT NULL DEFAULT 0,
  "day_of_week" INTEGER,
  "day_of_month" INTEGER,
  "integration_uid" INTEGER NOT NULL,
  "target" VARCHAR(256),
  "subject_template" VARCHAR(256),
  "message_template" TEXT,
  "enabled" BOOLEAN NOT NULL DEFAULT true,
  "last_run_at" TIMESTAMP WITH TIME ZONE,
  "last_status" VARCHAR(16),
  "last_error" VARCHAR(512),
  "next_run_at" TIMESTAMP WITH TIME ZONE,
  "vpbx_user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "cc_settings" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "default_sla_threshold" INTEGER NOT NULL DEFAULT 20,
  "journal_depth" INTEGER NOT NULL DEFAULT 50,
  "alert_thresholds" JSON,
  "alert_sound_enabled" BOOLEAN NOT NULL DEFAULT true,
  "role_permission_defaults" JSON,
  "permission_locks" JSON,
  "ui_visibility_defaults" JSON,
  "ui_visibility_locks" JSON,
  "notification_defaults" JSON,
  "notification_locks" JSON,
  "autopause_rules" JSON,
  "autopause_enabled" BOOLEAN NOT NULL DEFAULT true,
  "shift_policy" JSON,
  "callback_policy" JSON,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "vpbx_user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "cc_subjects" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(255) NOT NULL,
  "sort_order" INTEGER DEFAULT 0,
  "is_active" BOOLEAN DEFAULT true,
  PRIMARY KEY ("uid")
);
CREATE TABLE "cdr" (
  "calldate" VARCHAR(80),
  "clid" VARCHAR(80) NOT NULL DEFAULT '',
  "src" VARCHAR(80) NOT NULL DEFAULT '',
  "usrc" VARCHAR(80) NOT NULL DEFAULT '',
  "dst" VARCHAR(80) NOT NULL DEFAULT '',
  "dcontext" VARCHAR(80) NOT NULL DEFAULT '',
  "channel" VARCHAR(80) NOT NULL DEFAULT '',
  "dstchannel" VARCHAR(80) NOT NULL DEFAULT '',
  "lastapp" VARCHAR(80) NOT NULL DEFAULT '',
  "lastdata" VARCHAR(80) NOT NULL DEFAULT '',
  "duration" INTEGER NOT NULL DEFAULT 0,
  "billsec" INTEGER NOT NULL DEFAULT 0,
  "disposition" VARCHAR(45) NOT NULL DEFAULT '',
  "uniqueid" VARCHAR(80) NOT NULL,
  "linkedid" VARCHAR(80) NOT NULL DEFAULT '',
  "userfield" VARCHAR(255),
  "dialednum" VARCHAR(20),
  "transid" VARCHAR(80),
  "record" VARCHAR(255),
  "vpbx_user_uid" INTEGER DEFAULT 0,
  "useruid" INTEGER,
  "dstuseruid" INTEGER,
  PRIMARY KEY ("uniqueid")
);
CREATE TABLE "cloud_settings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "key" VARCHAR(128) NOT NULL UNIQUE,
  "value" TEXT,
  "description" VARCHAR(255),
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "conference_guest_tokens" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "room_uid" INTEGER NOT NULL,
  "token" VARCHAR(64) NOT NULL,
  "kind" "enum_conference_guest_tokens_kind" NOT NULL,
  "invite_name" VARCHAR(255),
  "expires_at" TIMESTAMP WITH TIME ZONE,
  "revoked_at" TIMESTAMP WITH TIME ZONE,
  "last_used_at" TIMESTAMP WITH TIME ZONE,
  "display_name" VARCHAR(64),
  "sip_id" VARCHAR(64),
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("uid")
);
CREATE TABLE "conference_meeting_participants" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "meeting_uid" INTEGER NOT NULL,
  "display_name" VARCHAR(255) NOT NULL,
  "role" "enum_conference_meeting_participants_role" NOT NULL DEFAULT 'participant',
  "is_guest" BOOLEAN NOT NULL DEFAULT false,
  "joined_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "left_at" TIMESTAMP WITH TIME ZONE,
  "caller_id_num" VARCHAR(64),
  "uniqueid" VARCHAR(64),
  "channel" VARCHAR(64),
  PRIMARY KEY ("uid")
);
CREATE TABLE "conference_meetings" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "room_uid" INTEGER NOT NULL,
  "started_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "ended_at" TIMESTAMP WITH TIME ZONE,
  "has_recording" BOOLEAN NOT NULL DEFAULT false,
  "recording_file_rel" VARCHAR(512),
  PRIMARY KEY ("uid")
);
CREATE TABLE "conference_room_moderators" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "room_uid" INTEGER NOT NULL,
  "endpoint_ref" VARCHAR(64) NOT NULL,
  "role" "enum_conference_room_moderators_role" NOT NULL DEFAULT 'moderator',
  PRIMARY KEY ("uid")
);
CREATE TABLE "conference_rooms" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "vpbx_user_uid" INTEGER NOT NULL,
  "number" VARCHAR(32) NOT NULL,
  "name" VARCHAR(255) NOT NULL,
  "kind" "enum_conference_rooms_kind" NOT NULL DEFAULT 'permanent',
  "entry_strictness" "enum_conference_rooms_entry_strictness" NOT NULL DEFAULT 'token_name',
  "pin" VARCHAR(32),
  "wait_marked" BOOLEAN NOT NULL DEFAULT false,
  "end_marked" BOOLEAN NOT NULL DEFAULT false,
  "record_mode" "enum_conference_rooms_record_mode" NOT NULL DEFAULT 'off',
  "notify_recording" BOOLEAN NOT NULL DEFAULT true,
  "invite_external_scope" "enum_conference_rooms_invite_external_scope" NOT NULL DEFAULT 'owner',
  "tariff_max_participants" INTEGER,
  "musiconhold" VARCHAR(128),
  "announce_join_leave" BOOLEAN NOT NULL DEFAULT false,
  "created_by" INTEGER,
  "created_at" TIMESTAMP WITH TIME ZONE,
  "updated_at" TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY ("uid")
);
CREATE TABLE "context_includes" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "context_uid" INTEGER NOT NULL,
  "include_uid" INTEGER NOT NULL,
  "priority" INTEGER NOT NULL DEFAULT 0,
  "user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "contexts" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(128) NOT NULL,
  "comment" VARCHAR(128) NOT NULL DEFAULT '',
  "user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "device_tokens" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "user_uid" INTEGER NOT NULL,
  "tenant_id" INTEGER NOT NULL,
  "token" VARCHAR(4096) NOT NULL,
  "platform" VARCHAR(32) DEFAULT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE,
  "updated_at" TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY ("id")
);
CREATE TABLE "directories" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "user_uid" INTEGER NOT NULL,
  "name" VARCHAR(255) NOT NULL,
  "description" VARCHAR(255) NOT NULL DEFAULT '',
  "lookup_field_uid" INTEGER DEFAULT NULL,
  "key_normalization" VARCHAR(16) NOT NULL DEFAULT 'none',
  "revision" INTEGER NOT NULL DEFAULT 0,
  "created_at" TIMESTAMP WITH TIME ZONE,
  "updated_at" TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY ("uid")
);
CREATE TABLE "directory_fields" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "directory_uid" INTEGER NOT NULL,
  "key" VARCHAR(64) NOT NULL,
  "label" VARCHAR(255) NOT NULL,
  "type" VARCHAR(16) NOT NULL,
  "required" BOOLEAN NOT NULL DEFAULT false,
  "position" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "directory_records" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "directory_uid" INTEGER NOT NULL,
  "lookup_value" VARCHAR(255) NOT NULL,
  "normalized_lookup_value" VARCHAR(255) NOT NULL,
  "match_kind" VARCHAR(24) NOT NULL,
  "priority" INTEGER NOT NULL,
  "values" JSON NOT NULL,
  "comment" VARCHAR(255) NOT NULL DEFAULT '',
  "created_at" TIMESTAMP WITH TIME ZONE,
  "updated_at" TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY ("uid")
);
CREATE TABLE "hub_module_pages" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "hub_code" VARCHAR(64) NOT NULL,
  "page_code" VARCHAR(64) NOT NULL,
  "path" VARCHAR(255),
  "sort_order" INTEGER DEFAULT 0,
  PRIMARY KEY ("id")
);
CREATE TABLE "hub_modules" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "code" VARCHAR(64) NOT NULL UNIQUE,
  "name" VARCHAR(128) NOT NULL,
  "kind" "enum_hub_modules_kind" NOT NULL DEFAULT 'base',
  "sort_order" INTEGER DEFAULT 0,
  "requires_cloud" BOOLEAN DEFAULT false,
  PRIMARY KEY ("id")
);
CREATE TABLE "ivrs" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(255) NOT NULL DEFAULT '',
  "timeout" VARCHAR(255),
  "timeout_response" VARCHAR(255),
  "timeout_digit" VARCHAR(255),
  "max_count" INTEGER NOT NULL DEFAULT 0,
  "active" SMALLINT NOT NULL DEFAULT 1,
  "direct_dial" SMALLINT NOT NULL DEFAULT 1,
  "prompts" JSON,
  "menu_items" JSON,
  "user_uid" INTEGER NOT NULL DEFAULT 0,
  "created_at" TIMESTAMP WITH TIME ZONE,
  "updated_at" TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY ("uid")
);
CREATE TABLE "komandor_claims" (
  "uid" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "operator_id" INTEGER,
  "operator_name" VARCHAR(255),
  "request_date" TIMESTAMP WITH TIME ZONE NOT NULL,
  "call_uniqueid" VARCHAR(128),
  "request_number" VARCHAR(64) UNIQUE,
  "store_id" INTEGER,
  "store_code" VARCHAR(64),
  "store_name" VARCHAR(512),
  "store_address" VARCHAR(512),
  "directors" JSON,
  "zdf" JSON,
  "extra_recipients" JSON,
  "extra_emails" TEXT,
  "channel" VARCHAR(64),
  "topic" VARCHAR(255),
  "subtopic" VARCHAR(255),
  "description" TEXT,
  "contact_info" TEXT,
  "client_phone" VARCHAR(32),
  "client_email" VARCHAR(255),
  "sentiment" VARCHAR(16) NOT NULL DEFAULT 'neutral',
  "department_log" JSON,
  "customer_response" TEXT,
  "attachment_name" VARCHAR(255),
  "dept_attachment_name" VARCHAR(255),
  "request_status" VARCHAR(20) NOT NULL DEFAULT 'new',
  "sms_status" VARCHAR(20) NOT NULL DEFAULT 'not_sent',
  "email_status" VARCHAR(20) NOT NULL DEFAULT 'not_sent',
  "store_email_status" VARCHAR(20) NOT NULL DEFAULT 'not_sent',
  "user_uid" INTEGER NOT NULL DEFAULT 0,
  "created_at" TIMESTAMP WITH TIME ZONE,
  "updated_at" TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY ("uid")
);
CREATE TABLE "komandor_dict" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "kind" VARCHAR(32) NOT NULL,
  "name" VARCHAR(255) NOT NULL,
  "parent_name" VARCHAR(255),
  "sort_order" INTEGER NOT NULL DEFAULT 0,
  "is_active" SMALLINT NOT NULL DEFAULT 1,
  PRIMARY KEY ("uid")
);
CREATE TABLE "komandor_stores" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "code" VARCHAR(32),
  "name" VARCHAR(255) NOT NULL,
  "address" VARCHAR(512),
  "city" VARCHAR(128),
  "directors" JSON,
  "zdf" JSON,
  "is_active" SMALLINT NOT NULL DEFAULT 1,
  "user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "modules_registry" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "code" VARCHAR(64) NOT NULL UNIQUE,
  "name" VARCHAR(128) NOT NULL,
  "description" TEXT,
  "version" VARCHAR(16) DEFAULT '1.0.0',
  "category" "enum_modules_registry_category" DEFAULT 'pbx',
  "is_core" BOOLEAN DEFAULT false,
  "is_paid" BOOLEAN DEFAULT false,
  "price_monthly" DECIMAL(10,2) DEFAULT 0,
  "is_published" BOOLEAN DEFAULT true,
  "requires_cloud" BOOLEAN DEFAULT false,
  "dependencies" JSON,
  "created_at" TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY ("id")
);
CREATE TABLE "musiconhold" (
  "name" VARCHAR(80),
  "mode" "enum_musiconhold_mode" DEFAULT 'playlist',
  "directory" VARCHAR(256),
  "sort" VARCHAR(10) DEFAULT 'random',
  "user_uid" INTEGER DEFAULT 0,
  PRIMARY KEY ("name")
);
CREATE TABLE "musiconhold_entry" (
  "name" VARCHAR(80),
  "position" INTEGER,
  "entry" VARCHAR(256) NOT NULL,
  PRIMARY KEY ("name", "position")
);
CREATE TABLE "notification_integrations" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(128) NOT NULL,
  "channel" "enum_notification_integrations_channel" NOT NULL,
  "config" JSON,
  "encrypted_credentials" TEXT,
  "user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "numbers" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(255),
  "comment" VARCHAR(255),
  "numbers" JSON,
  "vpbx_user_uid" INTEGER DEFAULT 0,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "pickup_groups" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(128) NOT NULL,
  "slug" VARCHAR(128) NOT NULL,
  "user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "prompts" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "filename" VARCHAR(50) NOT NULL,
  "comment" VARCHAR(128) NOT NULL DEFAULT '',
  "moh" VARCHAR(128) NOT NULL DEFAULT '',
  "user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "provision_templates" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(128) NOT NULL,
  "vendor" VARCHAR(64) DEFAULT '',
  "model" VARCHAR(64) DEFAULT '',
  "content" TEXT,
  "user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "ps_aors" (
  "id" VARCHAR(255),
  "contact" VARCHAR(255),
  "default_expiration" INTEGER,
  "mailboxes" VARCHAR(80),
  "max_contacts" INTEGER,
  "minimum_expiration" INTEGER,
  "maximum_expiration" INTEGER,
  "remove_existing" VARCHAR(40),
  "qualify_frequency" INTEGER,
  "authenticate_qualify" VARCHAR(40),
  "qualify_timeout" REAL,
  "outbound_proxy" VARCHAR(255),
  "support_path" VARCHAR(40),
  "voicemail_extension" VARCHAR(40),
  "remove_unavailable" VARCHAR(40),
  "qualify_2xx_only" VARCHAR(40),
  PRIMARY KEY ("id")
);
CREATE TABLE "ps_auths" (
  "id" VARCHAR(255),
  "auth_type" VARCHAR(40),
  "nonce_lifetime" INTEGER,
  "md5_cred" VARCHAR(40),
  "password" VARCHAR(80),
  "realm" VARCHAR(255),
  "username" VARCHAR(40),
  "refresh_token" VARCHAR(255),
  "oauth_clientid" VARCHAR(255),
  "oauth_secret" VARCHAR(255),
  "password_digest" VARCHAR(1024),
  "supported_algorithms_uas" VARCHAR(1024),
  "supported_algorithms_uac" VARCHAR(1024),
  PRIMARY KEY ("id")
);
CREATE TABLE "ps_contacts" (
  "id" VARCHAR(255),
  "uri" VARCHAR(511),
  "expiration_time" BIGINT,
  "qualify_frequency" INTEGER,
  "outbound_proxy" VARCHAR(255),
  "path" TEXT,
  "user_agent" VARCHAR(255),
  "qualify_timeout" REAL,
  "reg_server" VARCHAR(255),
  "authenticate_qualify" VARCHAR(40),
  "via_addr" VARCHAR(40),
  "via_port" INTEGER,
  "call_id" VARCHAR(255),
  "endpoint" VARCHAR(255),
  "prune_on_boot" VARCHAR(40),
  "qualify_2xx_only" VARCHAR(40),
  "updatedAt" TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY ("id")
);
CREATE TABLE "ps_endpoint_id_ips" (
  "id" VARCHAR(40),
  "endpoint" VARCHAR(40),
  "match" VARCHAR(80),
  "srv_lookups" "enum_ps_endpoint_id_ips_srv_lookups",
  "match_header" VARCHAR(255),
  "type" VARCHAR(40) DEFAULT 'identify',
  PRIMARY KEY ("id")
);
CREATE TABLE "ps_endpoints" (
  "id" VARCHAR(255),
  "transport" TEXT,
  "aors" VARCHAR(2048),
  "auth" VARCHAR(255),
  "context" TEXT,
  "disallow" VARCHAR(200),
  "allow" VARCHAR(200),
  "direct_media" TEXT,
  "connected_line_method" TEXT,
  "direct_media_method" TEXT,
  "direct_media_glare_mitigation" TEXT,
  "disable_direct_media_on_nat" TEXT,
  "dtmf_mode" TEXT,
  "external_media_address" TEXT,
  "force_rport" TEXT,
  "ice_support" TEXT,
  "identify_by" VARCHAR(80),
  "mailboxes" TEXT,
  "moh_suggest" TEXT,
  "outbound_auth" VARCHAR(255),
  "outbound_proxy" VARCHAR(255),
  "rewrite_contact" TEXT,
  "rtp_ipv6" TEXT,
  "rtp_symmetric" TEXT,
  "send_diversion" TEXT,
  "send_pai" TEXT,
  "send_rpid" TEXT,
  "timers_min_se" INTEGER,
  "timers" TEXT,
  "timers_sess_expires" INTEGER,
  "callerid" TEXT,
  "callerid_privacy" TEXT,
  "callerid_tag" TEXT,
  "100rel" TEXT,
  "aggregate_mwi" TEXT,
  "trust_id_inbound" TEXT,
  "trust_id_outbound" TEXT,
  "use_ptime" TEXT,
  "use_avpf" TEXT,
  "media_encryption" TEXT,
  "inband_progress" TEXT,
  "call_group" TEXT,
  "pickup_group" TEXT,
  "named_call_group" TEXT,
  "named_pickup_group" TEXT,
  "device_state_busy_at" INTEGER,
  "fax_detect" TEXT,
  "t38_udptl" TEXT,
  "t38_udptl_ec" TEXT,
  "t38_udptl_maxdatagram" INTEGER,
  "t38_udptl_nat" TEXT,
  "t38_udptl_ipv6" TEXT,
  "tone_zone" TEXT,
  "language" TEXT,
  "one_touch_recording" TEXT,
  "record_on_feature" TEXT,
  "record_off_feature" TEXT,
  "rtp_engine" TEXT,
  "allow_transfer" TEXT,
  "allow_subscribe" TEXT,
  "sdp_owner" TEXT,
  "sdp_session" TEXT,
  "tos_audio" VARCHAR(10),
  "tos_video" VARCHAR(10),
  "cos_audio" INTEGER,
  "cos_video" INTEGER,
  "sub_min_expiry" INTEGER,
  "from_domain" TEXT,
  "from_user" TEXT,
  "mwi_from_user" TEXT,
  "dtls_verify" TEXT,
  "dtls_rekey" TEXT,
  "dtls_cert_file" VARCHAR(200),
  "dtls_private_key" VARCHAR(200),
  "dtls_cipher" VARCHAR(200),
  "dtls_ca_file" VARCHAR(200),
  "dtls_ca_path" VARCHAR(200),
  "dtls_setup" TEXT,
  "srtp_tag_32" TEXT,
  "media_address" TEXT,
  "redirect_method" TEXT,
  "set_var" TEXT,
  "accountcode" VARCHAR(80),
  "user_eq_phone" TEXT,
  "moh_passthrough" TEXT,
  "media_encryption_optimistic" TEXT,
  "rpid_immediate" TEXT,
  "g726_non_standard" TEXT,
  "rtp_keepalive" INTEGER,
  "rtp_timeout" INTEGER,
  "rtp_timeout_hold" INTEGER,
  "bind_rtp_to_media_address" TEXT,
  "voicemail_extension" TEXT,
  "mwi_subscribe_replaces_unsolicited" TEXT,
  "deny" VARCHAR(95),
  "permit" VARCHAR(95),
  "acl" TEXT,
  "contact_deny" VARCHAR(95),
  "contact_permit" VARCHAR(95),
  "contact_acl" TEXT,
  "subscribe_context" TEXT,
  "fax_detect_timeout" INTEGER,
  "contact_user" VARCHAR(80),
  "preferred_codec_only" TEXT,
  "asymmetric_rtp_codec" TEXT,
  "rtcp_mux" TEXT,
  "allow_overlap" TEXT,
  "refer_blind_progress" TEXT,
  "notify_early_inuse_ringing" TEXT,
  "max_audio_streams" INTEGER,
  "max_video_streams" INTEGER,
  "webrtc" TEXT,
  "dtls_fingerprint" TEXT,
  "incoming_mwi_mailbox" TEXT,
  "bundle" TEXT,
  "dtls_auto_generate_cert" TEXT,
  "follow_early_media_fork" TEXT,
  "accept_multiple_sdp_answers" TEXT,
  "suppress_q850_reason_headers" TEXT,
  "trust_connected_line" TEXT,
  "send_connected_line" TEXT,
  "ignore_183_without_sdp" TEXT,
  "codec_prefs_incoming_offer" VARCHAR(128),
  "codec_prefs_outgoing_offer" VARCHAR(128),
  "codec_prefs_incoming_answer" VARCHAR(128),
  "codec_prefs_outgoing_answer" VARCHAR(128),
  "stir_shaken" TEXT,
  "send_history_info" TEXT,
  "allow_unauthenticated_options" TEXT,
  "t38_bind_udptl_to_media_address" TEXT,
  "geoloc_incoming_call_profile" VARCHAR(80),
  "geoloc_outgoing_call_profile" VARCHAR(80),
  "incoming_call_offer_pref" TEXT,
  "outgoing_call_offer_pref" TEXT,
  "stir_shaken_profile" VARCHAR(80),
  "security_negotiation" TEXT,
  "security_mechanisms" VARCHAR(512),
  "send_aoc" TEXT,
  "overlap_context" VARCHAR(80),
  "media_use_received_transport" TEXT,
  "force_avp" TEXT,
  "message_context" TEXT,
  "tenantid" VARCHAR(80),
  "suppress_moh_on_sendonly" TEXT,
  "follow_redirect_methods" VARCHAR(95),
  "department" VARCHAR(255) DEFAULT '',
  "provision_enabled" BOOLEAN DEFAULT false,
  "mac_address" VARCHAR(100) DEFAULT '',
  "provision_template_id" INTEGER,
  "pv_vars" TEXT,
  PRIMARY KEY ("id")
);
CREATE TABLE "ps_registrations" (
  "id" VARCHAR(40),
  "auth_rejection_permanent" "enum_ps_registrations_auth_rejection_permanent",
  "client_uri" VARCHAR(255),
  "contact_user" VARCHAR(40),
  "expiration" INTEGER,
  "max_retries" INTEGER,
  "outbound_auth" VARCHAR(40),
  "outbound_proxy" VARCHAR(40),
  "retry_interval" INTEGER,
  "forbidden_retry_interval" INTEGER,
  "server_uri" VARCHAR(255),
  "transport" VARCHAR(40),
  "support_path" "enum_ps_registrations_support_path",
  "line" "enum_ps_registrations_line",
  "endpoint" VARCHAR(40),
  "type" VARCHAR(40) DEFAULT 'registration',
  PRIMARY KEY ("id")
);
CREATE TABLE "queue_members_table" (
  "uniqueid" BIGINT GENERATED BY DEFAULT AS IDENTITY CHECK ("uniqueid" BETWEEN 0 AND 4294967295),
  "membername" VARCHAR(40),
  "queue_name" VARCHAR(128) NOT NULL,
  "interface" VARCHAR(128) NOT NULL,
  "penalty" INTEGER DEFAULT 0,
  "paused" INTEGER DEFAULT 0,
  "reason_paused" VARCHAR(128),
  "wrapuptime" INTEGER,
  "state_interface" VARCHAR(128),
  "vpbx_user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uniqueid")
);
CREATE TABLE "queue_table" (
  "name" VARCHAR(128),
  "musiconhold" VARCHAR(128),
  "announce" VARCHAR(128),
  "context" VARCHAR(128),
  "timeout" INTEGER,
  "strategy" VARCHAR(128),
  "retry" INTEGER,
  "wrapuptime" INTEGER,
  "maxlen" INTEGER,
  "servicelevel" INTEGER,
  "weight" INTEGER,
  "joinempty" VARCHAR(128),
  "leavewhenempty" VARCHAR(128),
  "ringinuse" BOOLEAN,
  "autofill" VARCHAR(8),
  "announce_frequency" INTEGER,
  "announce_holdtime" VARCHAR(128),
  "announce_round_seconds" INTEGER,
  "periodic_announce" VARCHAR(50),
  "periodic_announce_frequency" INTEGER,
  "queue_youarenext" VARCHAR(128),
  "queue_thereare" VARCHAR(128),
  "queue_callswaiting" VARCHAR(128),
  "queue_holdtime" VARCHAR(128),
  "queue_minutes" VARCHAR(128),
  "queue_seconds" VARCHAR(128),
  "queue_lessthan" VARCHAR(128),
  "queue_thankyou" VARCHAR(128),
  "queue_reporthold" VARCHAR(128),
  "monitor_format" VARCHAR(128),
  "monitor_join" BOOLEAN,
  "memberdelay" INTEGER,
  "timeoutrestart" BOOLEAN,
  "reportholdtime" BOOLEAN,
  "eventmemberstatus" BOOLEAN,
  "eventwhencalled" BOOLEAN,
  "setinterfacevar" BOOLEAN,
  "display_name" VARCHAR(255),
  "vpbx_user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("name")
);
CREATE TABLE "role_start_defaults" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "user_level" INTEGER NOT NULL UNIQUE,
  "start_path" VARCHAR(255) NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(255),
  "role" TEXT,
  "comment" VARCHAR(255),
  "vpbx_user_uid" INTEGER DEFAULT 0,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "route_directory_bindings" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "route_uid" INTEGER NOT NULL,
  "directory_uid" INTEGER NOT NULL,
  "position" INTEGER NOT NULL DEFAULT 0,
  "key_source" JSON NOT NULL,
  "match_mode" VARCHAR(16) NOT NULL DEFAULT 'on_match',
  "behavior_type" VARCHAR(32) NOT NULL,
  "behavior_params" JSON,
  "actions" JSON,
  "user_uid" INTEGER NOT NULL,
  PRIMARY KEY ("uid")
);
CREATE TABLE "route_templates" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(255) NOT NULL,
  "description" VARCHAR(512) NOT NULL DEFAULT '',
  "actions" JSON NOT NULL,
  "slots" JSON NOT NULL,
  "vpbx_user_uid" INTEGER DEFAULT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE,
  "updated_at" TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY ("uid")
);
CREATE TABLE "routes" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "context_uid" INTEGER NOT NULL,
  "name" VARCHAR(255) NOT NULL DEFAULT '',
  "extensions" JSON NOT NULL,
  "priority" INTEGER NOT NULL DEFAULT 0,
  "active" SMALLINT NOT NULL DEFAULT 1,
  "options" JSON,
  "webhooks" JSON,
  "actions" JSON NOT NULL,
  "raw_dialplan" TEXT,
  "user_uid" INTEGER NOT NULL DEFAULT 0,
  "created_at" TIMESTAMP WITH TIME ZONE,
  "updated_at" TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY ("uid")
);
CREATE TABLE "service_requests" (
  "uid" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "operator_id" INTEGER,
  "operator_name" VARCHAR(255),
  "call_received_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "call_uniqueid" VARCHAR(128),
  "request_number" VARCHAR(64) UNIQUE,
  "counterparty_type" VARCHAR(20) NOT NULL DEFAULT 'individual',
  "counterparty_name" VARCHAR(512),
  "account_or_inn" VARCHAR(64),
  "phone" VARCHAR(32),
  "territorial_zone" VARCHAR(128),
  "locality" VARCHAR(255),
  "district" VARCHAR(128),
  "address" VARCHAR(512),
  "topic" VARCHAR(128),
  "comment" TEXT,
  "production_comment" TEXT,
  "schedule_comment" TEXT,
  "sms_status" VARCHAR(20) NOT NULL DEFAULT 'not_sent',
  "scheduled_date" TIMESTAMP WITH TIME ZONE,
  "request_status" VARCHAR(20) NOT NULL DEFAULT 'new',
  "user_uid" INTEGER NOT NULL DEFAULT 0,
  "created_at" TIMESTAMP WITH TIME ZONE,
  "updated_at" TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY ("uid")
);
CREATE TABLE "stt_engines" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(128) NOT NULL,
  "type" VARCHAR(32) NOT NULL DEFAULT 'custom',
  "token" TEXT,
  "settings" JSON,
  "custom_url" VARCHAR(512),
  "auth_mode" VARCHAR(32) DEFAULT 'none',
  "custom_headers" JSON,
  "user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "system_settings" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "key" VARCHAR(128) NOT NULL UNIQUE,
  "value" TEXT,
  "category" VARCHAR(64) NOT NULL DEFAULT 'general',
  "updated_at" TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY ("uid")
);
CREATE TABLE "tenant_modules" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" INTEGER NOT NULL,
  "module_code" VARCHAR(64) NOT NULL,
  "status" "enum_tenant_modules_status" DEFAULT 'active',
  "activated_at" TIMESTAMP WITH TIME ZONE,
  "expires_at" TIMESTAMP WITH TIME ZONE,
  "billing_cycle" "enum_tenant_modules_billing_cycle" DEFAULT 'monthly',
  "last_billed_at" TIMESTAMP WITH TIME ZONE,
  "config" JSON,
  PRIMARY KEY ("id")
);
CREATE TABLE "tenant_role_start" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" INTEGER NOT NULL,
  "user_level" INTEGER NOT NULL,
  "start_path" VARCHAR(255) NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "tenant_settings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "vpbx_user_uid" INTEGER NOT NULL,
  "key" VARCHAR(128) NOT NULL,
  "value" TEXT,
  "category" VARCHAR(64) DEFAULT 'general',
  PRIMARY KEY ("id")
);
CREATE TABLE "tenants" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "uid" VARCHAR(36) NOT NULL,
  "name" VARCHAR(255) NOT NULL,
  "slug" VARCHAR(128),
  "owner_user_id" INTEGER NOT NULL,
  "vpbx_user_uid" INTEGER NOT NULL,
  "status" "enum_tenants_status" DEFAULT 'trial',
  "trial_ends_at" TIMESTAMP WITH TIME ZONE,
  "email" VARCHAR(255),
  "phone" VARCHAR(32),
  "company_inn" VARCHAR(32),
  "max_extensions" INTEGER DEFAULT 10,
  "max_trunks" INTEGER DEFAULT 2,
  "max_queues" INTEGER DEFAULT 3,
  "created_by" INTEGER,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "time_groups" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(100) NOT NULL,
  "comment" VARCHAR(255) DEFAULT '',
  "intervals" JSON NOT NULL,
  "user_uid" INTEGER NOT NULL DEFAULT 0,
  "created_at" TIMESTAMP WITH TIME ZONE,
  "updated_at" TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY ("uid")
);
CREATE TABLE "tts_engines" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(128) NOT NULL,
  "type" VARCHAR(32) NOT NULL DEFAULT 'custom',
  "token" TEXT,
  "settings" JSON,
  "custom_url" VARCHAR(512),
  "auth_mode" VARCHAR(32) DEFAULT 'none',
  "custom_headers" JSON,
  "user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "user_sessions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "user_id" INTEGER NOT NULL,
  "refreshToken" VARCHAR(512) NOT NULL,
  "userAgent" TEXT,
  "ipAddress" VARCHAR(45),
  "expiresAt" BIGINT NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "users" (
  "uniqueid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "login" VARCHAR(255),
  "name" VARCHAR(255),
  "passwd" VARCHAR(255),
  "email" VARCHAR(255),
  "exten" VARCHAR(255),
  "level" INTEGER DEFAULT 2,
  "role" INTEGER,
  "numbers_id" INTEGER,
  "permit_extens" VARCHAR(255),
  "listbook_edit" INTEGER DEFAULT 0,
  "oper_chanspy" INTEGER DEFAULT 0,
  "outbound_posttime" INTEGER DEFAULT 0,
  "suspension_time" INTEGER DEFAULT 0,
  "inactive_time" INTEGER DEFAULT 0,
  "vpbx_user_uid" INTEGER DEFAULT 0,
  "activationCode" VARCHAR(255),
  "activationExpires" BIGINT,
  "isActivated" BOOLEAN DEFAULT false,
  "avatar" VARCHAR(255),
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("uniqueid")
);
CREATE TABLE "vm_access_tokens" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "token" VARCHAR(64) NOT NULL,
  "message_uid" INTEGER NOT NULL,
  "vpbx_user_uid" INTEGER NOT NULL DEFAULT 0,
  "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "revoked_at" TIMESTAMP WITH TIME ZONE,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("uid")
);
CREATE TABLE "voice_robot_cdr" (
  "uid" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "robot_id" INTEGER NOT NULL,
  "robot_name" VARCHAR(255),
  "call_uniqueid" VARCHAR(128),
  "channel_id" VARCHAR(255),
  "session_id" VARCHAR(255),
  "caller_id" VARCHAR(64),
  "caller_name" VARCHAR(128),
  "started_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "ended_at" TIMESTAMP WITH TIME ZONE,
  "duration_seconds" INTEGER NOT NULL DEFAULT 0,
  "disposition" VARCHAR(32) NOT NULL DEFAULT 'completed',
  "last_action" VARCHAR(64),
  "transfer_target" VARCHAR(128),
  "total_steps" INTEGER NOT NULL DEFAULT 0,
  "matched_keywords_count" INTEGER NOT NULL DEFAULT 0,
  "no_match_count" INTEGER NOT NULL DEFAULT 0,
  "avg_confidence" DECIMAL(5,2),
  "collected_slots" JSON,
  "transcript" TEXT,
  "tags" JSON,
  "user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "voice_robot_data_lists" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "robot_id" INTEGER NOT NULL,
  "name" VARCHAR(255) NOT NULL,
  "description" TEXT,
  "columns" JSON NOT NULL,
  "rows" JSON NOT NULL,
  "user_uid" INTEGER NOT NULL DEFAULT 0,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("uid")
);
CREATE TABLE "voice_robot_keyword_groups" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "robot_id" INTEGER NOT NULL,
  "name" VARCHAR(255) NOT NULL,
  "description" TEXT,
  "priority" INTEGER NOT NULL DEFAULT 0,
  "active" SMALLINT NOT NULL DEFAULT 1,
  "is_global" SMALLINT NOT NULL DEFAULT 0,
  "user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "voice_robot_keywords" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "group_id" INTEGER NOT NULL,
  "keywords" TEXT NOT NULL,
  "negative_keywords" JSON,
  "synonyms" JSON,
  "actions" JSON,
  "bot_action" JSON,
  "priority" INTEGER NOT NULL DEFAULT 0,
  "max_repeats" INTEGER NOT NULL DEFAULT 0,
  "escalation_action" JSON,
  "comment" VARCHAR(512),
  "tag" VARCHAR(255),
  "user_uid" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("uid")
);
CREATE TABLE "voice_robot_logs" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "robot_id" INTEGER,
  "call_uniqueid" VARCHAR(128),
  "session_id" VARCHAR(255),
  "channel_id" VARCHAR(255),
  "caller_id" VARCHAR(255),
  "step_number" INTEGER NOT NULL DEFAULT 0,
  "matched_group_id" INTEGER,
  "recognized_text" TEXT,
  "raw_stt_json" JSON,
  "audio_file_path" VARCHAR(512),
  "matched_keyword_id" INTEGER,
  "match_confidence" DECIMAL(5,2),
  "action_taken" VARCHAR(512),
  "stt_duration_ms" INTEGER,
  "matching_score" REAL,
  "duration_ms" INTEGER,
  "ai_response" TEXT,
  "flow_action" JSON,
  "user_uid" INTEGER,
  "timestamp" TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY ("uid")
);
CREATE TABLE "voice_robots" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(255) NOT NULL,
  "description" TEXT,
  "active" SMALLINT NOT NULL DEFAULT 1,
  "language" VARCHAR(16) NOT NULL DEFAULT 'ru-RU',
  "stt_engine_id" INTEGER,
  "tts_engine_id" INTEGER,
  "greeting_prompts" JSON,
  "greeting_tts_text" TEXT,
  "initial_group_id" INTEGER,
  "vad_config" JSON,
  "fallback_action" JSON,
  "fallback_bot_action" JSON,
  "max_retries_action" JSON,
  "max_retries_bot_action" JSON,
  "max_conversation_steps" INTEGER NOT NULL DEFAULT 0,
  "silence_timeout_seconds" INTEGER NOT NULL DEFAULT 15,
  "max_inactivity_repeats" INTEGER NOT NULL DEFAULT 3,
  "webhook_url" VARCHAR(512),
  "webhook_method" VARCHAR(8) NOT NULL DEFAULT 'POST',
  "telegram_chat_id" VARCHAR(128),
  "email_notify" VARCHAR(255),
  "external_host" VARCHAR(255),
  "tts_mode" VARCHAR(20) NOT NULL DEFAULT 'batch',
  "tts_cache_max_age_days" INTEGER NOT NULL DEFAULT 0,
  "stt_mode" VARCHAR(20) NOT NULL DEFAULT 'hybrid',
  "user_uid" INTEGER NOT NULL DEFAULT 0,
  "created_at" TIMESTAMP WITH TIME ZONE,
  "updated_at" TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY ("uid")
);
CREATE TABLE "voicemail_messages" (
  "uid" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "vpbx_user_uid" INTEGER NOT NULL DEFAULT 0,
  "uniqueid" VARCHAR(128) NOT NULL,
  "file_rel" VARCHAR(512) NOT NULL,
  "record_status" VARCHAR(32) NOT NULL DEFAULT '',
  "caller_id" VARCHAR(64) NOT NULL DEFAULT '',
  "exten" VARCHAR(64) NOT NULL DEFAULT '',
  "duration_sec" INTEGER,
  "notify_status" VARCHAR(16) NOT NULL DEFAULT 'pending',
  "transcript_status" VARCHAR(16) NOT NULL DEFAULT 'pending',
  "notify_attempts" INTEGER NOT NULL DEFAULT 0,
  "transcript_attempts" INTEGER NOT NULL DEFAULT 0,
  "next_notify_at" TIMESTAMP WITH TIME ZONE,
  "scan_locked_until" TIMESTAMP WITH TIME ZONE,
  "transcript" TEXT,
  "summary" TEXT,
  "notify_error" TEXT,
  "notify_dispatch" TEXT,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("uid")
);
CREATE TABLE "webhook_failures" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY CHECK ("id" BETWEEN 0 AND 4294967295),
  "route_uid" VARCHAR(64) NOT NULL,
  "event" VARCHAR(32) NOT NULL,
  "url" VARCHAR(512) NOT NULL,
  "payload" JSON NOT NULL,
  "headers" JSON NOT NULL,
  "error" TEXT,
  "attempts" SMALLINT DEFAULT 3 CHECK ("attempts" BETWEEN 0 AND 255),
  "failed_at" TIMESTAMP WITH TIME ZONE,
  "retried_at" TIMESTAMP WITH TIME ZONE,
  "resolved" BOOLEAN DEFAULT false,
  PRIMARY KEY ("id")
);

CREATE INDEX "idx_ac_base_fields_base_uid_fk" ON "ac_base_fields" ("base_uid");
CREATE INDEX "idx_ac_contact_phones_contact_uid_fk" ON "ac_contact_phones" ("contact_uid");
CREATE INDEX "idx_ac_contacts_base_uid_fk" ON "ac_contacts" ("base_uid");
CREATE INDEX "idx_bt_tenant_date" ON "billing_transactions" ("tenant_id", "created_at");
CREATE UNIQUE INDEX "uq_device_tokens_user_tenant" ON "device_tokens" ("user_uid", "tenant_id");
CREATE INDEX "idx_device_tokens_tenant" ON "device_tokens" ("tenant_id");
CREATE INDEX "idx_directories_user_uid" ON "directories" ("user_uid");
CREATE UNIQUE INDEX "uq_directories_tenant_name" ON "directories" ("user_uid", "name");
CREATE UNIQUE INDEX "uq_directory_fields_key" ON "directory_fields" ("directory_uid", "key");
CREATE UNIQUE INDEX "uq_directory_exact_key" ON "directory_records" ("directory_uid", "normalized_lookup_value", "match_kind");
CREATE INDEX "idx_directory_patterns" ON "directory_records" ("directory_uid", "match_kind", "priority");
CREATE UNIQUE INDEX "uq_hub_module_page" ON "hub_module_pages" ("hub_code", "page_code");
CREATE INDEX "idx_hub_module_pages_hub" ON "hub_module_pages" ("hub_code");
CREATE UNIQUE INDEX "uq_hub_modules_code" ON "hub_modules" ("code");
CREATE INDEX "idx_route_directory_bindings_route_uid_fk" ON "route_directory_bindings" ("route_uid");
CREATE INDEX "idx_route_directory_bindings_directory_uid_fk" ON "route_directory_bindings" ("directory_uid");
CREATE INDEX "idx_rdb_user_uid" ON "route_directory_bindings" ("user_uid");
CREATE INDEX "idx_route_templates_vpbx_user_uid" ON "route_templates" ("vpbx_user_uid");
CREATE UNIQUE INDEX "uq_route_templates_tenant_name" ON "route_templates" ("vpbx_user_uid", "name");
CREATE INDEX "idx_routes_context_uid_fk" ON "routes" ("context_uid");
CREATE UNIQUE INDEX "uq_tenant_module" ON "tenant_modules" ("tenant_id", "module_code");
CREATE INDEX "idx_tm_tenant" ON "tenant_modules" ("tenant_id");
CREATE UNIQUE INDEX "uq_tenant_role_start" ON "tenant_role_start" ("tenant_id", "user_level");
CREATE INDEX "idx_voice_robot_data_lists_robot_id_fk" ON "voice_robot_data_lists" ("robot_id");
CREATE INDEX "idx_voice_robot_keyword_groups_robot_id_fk" ON "voice_robot_keyword_groups" ("robot_id");
CREATE INDEX "idx_voice_robot_keywords_group_id_fk" ON "voice_robot_keywords" ("group_id");

ALTER TABLE "ac_base_fields" ADD FOREIGN KEY ("base_uid") REFERENCES "ac_bases" ("uid") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "ac_contact_phones" ADD FOREIGN KEY ("contact_uid") REFERENCES "ac_contacts" ("uid") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "ac_contacts" ADD FOREIGN KEY ("base_uid") REFERENCES "ac_bases" ("uid") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "directory_fields" ADD FOREIGN KEY ("directory_uid") REFERENCES "directories" ("uid") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "directory_records" ADD FOREIGN KEY ("directory_uid") REFERENCES "directories" ("uid") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "hub_module_pages" ADD FOREIGN KEY ("hub_code") REFERENCES "hub_modules" ("code") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "route_directory_bindings" ADD FOREIGN KEY ("route_uid") REFERENCES "routes" ("uid") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "route_directory_bindings" ADD FOREIGN KEY ("directory_uid") REFERENCES "directories" ("uid") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "routes" ADD FOREIGN KEY ("context_uid") REFERENCES "contexts" ("uid") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "voice_robot_data_lists" ADD FOREIGN KEY ("robot_id") REFERENCES "voice_robots" ("uid") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "voice_robot_keyword_groups" ADD FOREIGN KEY ("robot_id") REFERENCES "voice_robots" ("uid") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "voice_robot_keywords" ADD FOREIGN KEY ("group_id") REFERENCES "voice_robot_keyword_groups" ("uid") ON DELETE CASCADE ON UPDATE CASCADE;
