ALTER TABLE tenants ADD COLUMN IF NOT EXISTS sa_own_models BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS sa_project_model_override BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS sa_stt_provider_uid INTEGER NULL;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS sa_llm_provider_uid INTEGER NULL;
