-- PostgreSQL Hub layout schema for a configured single-cabinet box.
-- Catalog rows are inserted once and operator edits are preserved on replay.
ALTER TYPE "enum_hub_modules_kind" ADD VALUE IF NOT EXISTS 'off';

CREATE TABLE IF NOT EXISTS tenant_hub_layout (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INTEGER NOT NULL REFERENCES tenants(id),
  hub_code VARCHAR(64) NOT NULL REFERENCES hub_modules(code),
  sort_order INTEGER NOT NULL DEFAULT 0,
  visible BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT uq_tenant_hub_layout UNIQUE (tenant_id, hub_code)
);

INSERT INTO hub_modules (code, name, kind, sort_order, requires_cloud) VALUES
  ('overview', 'Overview', 'base', 0, false),
  ('core', 'Core', 'base', 10, false),
  ('apps', 'Apps', 'base', 20, false),
  ('system', 'System', 'base', 30, false),
  ('callcenter', 'Call Center', 'market', 40, false),
  ('analytics', 'Analytics', 'market', 50, false),
  ('ai', 'AI', 'market', 60, false),
  ('autodial', 'Autodial', 'market', 70, false),
  ('speech_analytics', 'Speech analytics', 'market', 80, false),
  ('ai_voice_robots', 'AI robots', 'market', 90, false)
ON CONFLICT (code) DO NOTHING;

INSERT INTO hub_module_pages (hub_code, page_code, path, sort_order) VALUES
  ('overview', 'dashboard', '/', 0),
  ('core', 'endpoints', '/endpoints', 10),
  ('core', 'contexts', '/contexts', 20),
  ('core', 'trunks', '/trunks', 30),
  ('core', 'routes', '/routes', 40),
  ('core', 'time_groups', '/time-groups', 50),
  ('core', 'directories', '/directories', 60),
  ('core', 'provision', '/provision-templates', 70),
  ('apps', 'ivr', '/ivrs', 10),
  ('apps', 'queues', '/queues', 20),
  ('apps', 'prompts', '/prompts', 30),
  ('apps', 'moh', '/moh', 40),
  ('apps', 'voice_robot', '/voice-robots', 50),
  ('apps', 'call_groups', '/call-groups', 60),
  ('apps', 'conferences', '/conferences', 65),
  ('apps', 'integrations', '/integrations', 70),
  ('system', 'users_roles', '/users', 10),
  ('system', 'roles', '/roles', 20),
  ('system', 'numbers', '/numbers', 30),
  ('system', 'settings', '/settings', 40),
  ('system', 'tts_engines', '/settings/tts-engines', 50),
  ('system', 'stt_engines', '/settings/stt-engines', 60),
  ('system', 'audit_log', '/audit-log', 70),
  ('system', 'tenant_modules', '/my-modules', 80),
  ('system', 'ai_providers', '/ai-providers', 90),
  ('callcenter', 'cc_agent', '/callcenter/agent', 20),
  ('callcenter', 'cc_supervisor', '/callcenter/supervisor', 30),
  ('callcenter', 'cc_reports', '/callcenter/reports', 40),
  ('callcenter', 'cc_settings', '/callcenter/settings', 50),
  ('autodial', 'autodial_campaigns', '/autodial', 10),
  ('autodial', 'autodial_bases', '/autodial/bases', 20),
  ('autodial', 'autodial_monitor', '/autodial/monitor', 30),
  ('autodial', 'autodial_reports', '/autodial/reports', 40),
  ('analytics', 'reports', '/reports', 10),
  ('analytics', 'cdr', '/reports/cdr', 20),
  ('analytics', 'voice_robot_cdr', '/reports/voice-robot-cdr', 30),
  ('ai', 'ai_agents', '/ai-agents', 20),
  ('speech_analytics', 'speech_analytics_conversations', '/speech-analytics/conversations', 10),
  ('speech_analytics', 'speech_analytics_projects', '/speech-analytics/projects', 15),
  ('speech_analytics', 'speech_analytics_dashboard', '/speech-analytics/dashboard', 16),
  ('speech_analytics', 'speech_analytics_connections', '/speech-analytics/connections', 20),
  ('ai_voice_robots', 'ai_voice_robots_landing', '/ai-robots', 10),
  ('ai_voice_robots', 'ai_voice_robots_studio', '/ai-robots/studio', 12),
  ('ai_voice_robots', 'ai_voice_robots_sessions', '/ai-robots/sessions', 14),
  ('ai_voice_robots', 'ai_voice_robots_preview', '/ai-robots/preview', 16),
  ('ai_voice_robots', 'ai_voice_robots_sip', '/ai-robots/sip', 17),
  ('ai_voice_robots', 'ai_voice_robots_tools', '/ai-robots/tools', 18),
  ('ai_voice_robots', 'ai_voice_robots_knowledge', '/ai-robots/knowledge', 19),
  ('ai_voice_robots', 'ai_voice_robots_connections', '/ai-robots/connections', 20)
ON CONFLICT (hub_code, page_code) DO NOTHING;

INSERT INTO hub_module_pages (hub_code, page_code, path, sort_order)
VALUES ('core', 'route_templates', '/route-templates', 45)
ON CONFLICT (hub_code, page_code) DO NOTHING;
