-- Durable originate holds and campaign fencing belong to versioned schema.
ALTER TABLE ac_campaigns ADD COLUMN IF NOT EXISTS applied_revision INTEGER NULL;
ALTER TABLE ac_campaigns ADD COLUMN IF NOT EXISTS apply_error VARCHAR(255) NULL;
ALTER TABLE ac_campaigns ADD COLUMN IF NOT EXISTS pacer_owner VARCHAR(64) NULL;
ALTER TABLE ac_campaigns ADD COLUMN IF NOT EXISTS pacer_heartbeat_at TIMESTAMP WITH TIME ZONE NULL;
UPDATE ac_campaigns SET applied_revision = revision WHERE applied_revision IS NULL;
CREATE TABLE IF NOT EXISTS ac_channel_reservations (
 uid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 vpbx_user_uid INTEGER NOT NULL,
 campaign_uid INTEGER NOT NULL,
 task_uid INTEGER NOT NULL,
 trunk_id VARCHAR(128) NOT NULL,
 owner VARCHAR(64) NOT NULL,
 expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_ac_res_task ON ac_channel_reservations (task_uid);
CREATE INDEX IF NOT EXISTS idx_ac_res_trunk ON ac_channel_reservations (vpbx_user_uid, trunk_id, expires_at);
