/**
 * Generates global Asterisk subroutine contexts used by all tenants.
 *
 * These subroutines are SHARED across all routes/tenants — route-specific
 * data is passed via channel variables (__WH_OA, __HH_ROUTE_UID, etc.)
 * set in the per-route dialplan, not baked into the subroutine itself.
 *
 * Generated contexts:
 *   [krsk-on-answer]      — Called via Dial() U() option on caller channel when agent answers
 *   [krsk-hangup-handler] — Registered via CHANNEL(hangup_handler_push), runs on channel teardown
 *
 * @see https://docs.asterisk.org/Asterisk_22_Documentation/API_Documentation/Dialplan_Applications/Dial — U() option
 * @see https://docs.asterisk.org/Asterisk_22_Documentation/API_Documentation/Dialplan_Applications/Hangup — hangup_handler
 */
export class DialplanSubroutinesUtil {
  /**
   * Generate the full [krsk-on-answer] + [krsk-hangup-handler] subroutine file content.
   *
   * @param backendUrl  - Internal backend URL reachable from Asterisk (e.g. http://127.0.0.1:5010/api)
   * @param apiKey      - Optional API key for internal endpoint authentication
   * @param recordsBase - Absolute path to recordings base dir (e.g. /usr/records)
   */
  static generate(backendUrl: string, apiKey?: string, recordsBase = '/usr/records'): string {
    const keyParam = apiKey ? `&api_key=${encodeURIComponent(apiKey)}` : '';
    const lines: string[] = [];

    lines.push('; ============================================================');
    lines.push('; Krasterisk global subroutines — auto-generated, do not edit');
    lines.push('; Generated by DialplanSubroutinesUtil');
    lines.push('; ============================================================');
    lines.push('');

    // --------------------------------------------------------
    // [krsk-on-answer]
    // --------------------------------------------------------
    // Called via Dial() U(krsk-on-answer,s,1(dial)) or U(krsk-on-answer,s,1(group))
    // Runs on the CALLER channel — all caller variables are accessible.
    //
    // ARG1 = source type: 'dial' | 'group'
    //   Used by backend to set context-appropriate fields in the webhook payload.
    //
    // Variables available (set in per-route dialplan with __ prefix):
    //   ${WH_OA}         — "1" if on_answer webhook is configured for this route
    //   ${HH_ROUTE_UID}  — route UID used to look up webhook config in backend
    //   ${CALLERID(num)} — caller number
    //   ${UNIQUEID}      — channel unique ID for CDR correlation
    //   ${CDR(vpbx_user_uid)} — tenant ID
    //   ${DIALEDPEERNUMBER}   — answered peer (PJSIP endpoint)
    lines.push('[krsk-on-answer]');
    lines.push('exten => s,1,NoOp(Krasterisk on-answer: route=${HH_ROUTE_UID} src=${ARG1})');
    // Guard: skip if flag not set (route has no on_answer webhook)
    lines.push('same  => n,ExecIf($["${WH_OA}" != "1"]?Return())');
    // Short timeouts: on_answer is real-time, we return immediately to Asterisk
    lines.push('same  => n,Set(CURLOPT(conntimeout)=3)');
    lines.push('same  => n,Set(CURLOPT(timeout)=5)');
    // Fire webhook — backend enqueues async delivery, returns "ok" immediately
    lines.push(`same  => n,Set(CURL_OA=\${CURL(${backendUrl}/internal/dialplan/on-answer,route_uid=\${HH_ROUTE_UID}&uniqueid=\${URIENCODE(\${UNIQUEID})}&clid=\${URIENCODE(\${CALLERID(num)})}&member=\${URIENCODE(\${DIALEDPEERNUMBER})}&user_uid=\${CDR(vpbx_user_uid)}&source=\${ARG1}${keyParam})})`);
    lines.push('same  => n,Set(CURLOPT(conntimeout)=)');
    lines.push('same  => n,Set(CURLOPT(timeout)=)');
    lines.push('same  => n,Return()');
    lines.push('');

    // --------------------------------------------------------
    // [krsk-hangup-handler]
    // --------------------------------------------------------
    // Registered via: Set(CHANNEL(hangup_handler_push)=krsk-hangup-handler,s,1)
    // Executes on the channel when it hangs up — AFTER MixMonitor writes the WAV file.
    //
    // Responsibilities (in order):
    //   1. Convert WAV → MP3 via ffmpeg (synchronous inside handler = MP3 guaranteed ready)
    //   2. Notify backend via on_hangup webhook (MP3 URL is valid at this point)
    //
    // Variables available (set earlier in route dialplan):
    //   ${fname}   — recording filename (without extension)
    //   ${path}    — date subdirectory (YYYYMMDD)
    //   ${WH_OH}   — "1" if on_hangup webhook is configured
    //   ${HH_ROUTE_UID} — route UID
    //   ${CDR(vpbx_user_uid)} — tenant ID
    //   ${CDR(billsec)}       — answered duration in seconds
    //   ${CDR(disposition)}   — ANSWERED / NO ANSWER / BUSY / FAILED
    //   ${CDR(record)}        — relative path stored in CDR (rpath/path/fname, no extension)
    lines.push('[krsk-hangup-handler]');
    lines.push('exten => s,1,NoOp(Krasterisk hangup-handler: route=${HH_ROUTE_UID} file=${fname})');

    // FFmpeg conversion: synchronous in hangup_handler = MP3 is ready BEFORE we fire the webhook.
    // This is the critical difference from MixMonitor postprocess (async & race condition with webhooks).
    // -y          : overwrite without prompt
    // -i ...wav   : input WAV from MixMonitor
    // -codec:a libmp3lame -b:a 32k -ar 8000 -ac 1 : 32kbps mono 8kHz telephony MP3
    // -loglevel quiet : no stdout noise in Asterisk log
    // && rm -f    : remove WAV after successful conversion only
    // nice -n 10  : background priority, won't spike Asterisk CPU
    //
    // ExecIf: skip conversion if fname is empty (route without recording)
    lines.push(`same  => n,ExecIf($["\${fname}" != ""]?System(nice -n 10 /usr/bin/ffmpeg -y -i ${recordsBase}/\${CDR(record)}.wav -codec:a libmp3lame -b:a 32k -ar 8000 -ac 1 ${recordsBase}/\${CDR(record)}.mp3 -loglevel quiet && rm -f ${recordsBase}/\${CDR(record)}.wav))`);

    // on_hangup webhook: fires only if route has on_hangup configured (WH_OH=1)
    // At this point MP3 is guaranteed to exist (ffmpeg ran synchronously above)
    lines.push('same  => n,ExecIf($["${WH_OH}" != "1"]?Return())');
    lines.push('same  => n,Set(CURLOPT(conntimeout)=3)');
    lines.push('same  => n,Set(CURLOPT(timeout)=5)');
    lines.push(`same  => n,Set(CURL_HH=\${CURL(${backendUrl}/internal/dialplan/on-hangup,route_uid=\${HH_ROUTE_UID}&uniqueid=\${URIENCODE(\${UNIQUEID})}&clid=\${URIENCODE(\${CALLERID(num)})}&duration=\${CDR(billsec)}&disposition=\${CDR(disposition)}&record_path=\${URIENCODE(\${CDR(record)})}&user_uid=\${CDR(vpbx_user_uid)}${keyParam})})`);
    lines.push('same  => n,Set(CURLOPT(conntimeout)=)');
    lines.push('same  => n,Set(CURLOPT(timeout)=)');
    lines.push('same  => n,Return()');
    lines.push('');

    return lines.join('\n');
  }
}
