[settings]
ps_endpoints => odbc,krasterisk
ps_auths => odbc,krasterisk
ps_aors => odbc,krasterisk
ps_contacts => odbc,krasterisk
ps_domain_aliases => odbc,krasterisk
ps_endpoint_id_ips => odbc,krasterisk
ps_registrations => odbc,krasterisk
queues => odbc,krasterisk,queue_table
queue_members => odbc,krasterisk,queue_members_table
queue_log => odbc,krasterisk
