#!/usr/bin/env bash
# Repair lab config that was pulled into the production dialplan glob.
#
# /etc/asterisk/extensions.conf has `#include krasterisk/*/*.conf`.
# Everything under krasterisk/<dir>/*.conf is parsed as dialplan.
# Lab PJSIP snippets and extra #include/#tryinclude of the same files
# produce: duplicate [krasterisk-ai-generated], duplicate srtp, and
# pbx_config "Unknown directive: type" from pjsip.conf.
set -euo pipefail

EXT=/etc/asterisk/extensions.conf
LAB=/etc/asterisk/krasterisk/ai-lab
PJSIP_MAIN=/etc/asterisk/pjsip.conf
PJSIP_DST_DIR=/etc/asterisk/pjsip.d
PJSIP_DST="$PJSIP_DST_DIR/ai-lab.conf"
STAMP=$(date +%Y%m%d%H%M%S)
BACKUP=/root/asterisk-ai-lab-glob-fix-$STAMP
MODULES=/etc/asterisk/modules.conf

install -d "$BACKUP" "$LAB" "$PJSIP_DST_DIR"
cp -a "$EXT" "$PJSIP_MAIN" "$MODULES" "$LAB" "$BACKUP/"

# 1. Lab extensions.conf must be the isolated MixMonitor context only.
#    Previous probes appended generated.conf twice and #include srtp-exten.
python3 - <<'PY'
from pathlib import Path
p = Path("/etc/asterisk/krasterisk/ai-lab/extensions.conf")
text = p.read_text(encoding="utf-8", errors="replace")
cut = text.find("; generated by route-recording.util")
if cut == -1:
    cut = text.find("[krasterisk-ai-generated]")
if cut != -1:
    text = text[:cut]
# Drop nested includes — glob already loads sibling *.conf
lines = []
for line in text.splitlines(True):
    if "krasterisk/ai-lab/srtp-exten.conf" in line:
        continue
    if "krasterisk/ai-lab/generated.conf" in line:
        continue
    if "krasterisk/ai-lab/pjsip.conf" in line:
        continue
    lines.append(line)
out = "".join(lines).rstrip() + "\n"
p.write_text(out, encoding="utf-8")
print(f"lab extensions.conf kept {len(out.splitlines())} lines")
PY

# 2. generated.conf is already loaded by the glob. Extra tryinclude duplicates it.
if grep -q 'krasterisk/ai-lab/generated.conf' "$EXT"; then
  tmp=$(mktemp)
  grep -v 'krasterisk/ai-lab/generated.conf' "$EXT" >"$tmp"
  mv "$tmp" "$EXT"
  echo "removed extra generated.conf include from extensions.conf"
fi

# 3. Move PJSIP snippet out of the dialplan glob.
if [ -f "$LAB/pjsip.conf" ]; then
  cp -a "$LAB/pjsip.conf" "$PJSIP_DST"
  rm -f "$LAB/pjsip.conf"
  echo "moved $LAB/pjsip.conf -> $PJSIP_DST"
fi
if grep -q 'krasterisk/ai-lab/pjsip.conf' "$PJSIP_MAIN"; then
  sed -i 's#krasterisk/ai-lab/pjsip.conf#pjsip.d/ai-lab.conf#g' "$PJSIP_MAIN"
  echo "updated pjsip.conf tryinclude to pjsip.d/ai-lab.conf"
elif ! grep -q 'pjsip.d/ai-lab.conf' "$PJSIP_MAIN"; then
  printf '\n#tryinclude pjsip.d/ai-lab.conf\n' >> "$PJSIP_MAIN"
  echo "added #tryinclude pjsip.d/ai-lab.conf"
fi

# 4. Missing / unused modules that ERROR on every start (unrelated to AMD).
noload_mod() {
  local name="$1"
  if grep -qE "^[[:space:]]*load[[:space:]]*=[[:space:]]*${name}" "$MODULES"; then
    sed -i "s/^[[:space:]]*load[[:space:]]*=[[:space:]]*${name}/noload = ${name}/" "$MODULES"
    echo "noload $name"
  elif ! grep -qE "^[[:space:]]*noload[[:space:]]*=[[:space:]]*${name}" "$MODULES"; then
    printf '\nnoload = %s\n' "$name" >> "$MODULES"
    echo "appended noload $name"
  fi
}
noload_mod 'res_xmldoc.so'
noload_mod 'cdr_manager.so'

echo "backup $BACKUP"
echo "--- remaining ai-lab ---"
ls -l "$LAB"
echo "--- reload dialplan ---"
asterisk -rx 'dialplan reload' || true
asterisk -rx 'dialplan show krasterisk-ai-generated' | head -n 20 || true
asterisk -rx 'dialplan show krasterisk-ai-lab-srtp' | head -n 12 || true
echo "--- modules ---"
asterisk -rx 'module show like app_amd'
asterisk -rx 'module show like waitforsilence'
echo "FIX_AI_LAB_GLOB_OK"
