---
- name: Install Docker engine and Compose
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose-v2
    state: present

- name: Enable Docker
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
